### ISSUE TITLE
selinux-policy-targeted-35.10-1.fc35.noarch seems to break moby-engine

### ISSUE THREAD

**Issue by mnk-se** [fedora-selinux/selinux-policy#1015]
After installing the selinux-policy-targeted-35.10-1.fc35.noarch update, docker would no longer run.
I had to downgrade to selinux-policy-targeted-35.9-1.fc35.noarch and run `dnf reinstall container-selinux` to make it work again.

**Comment by zpytela** [comment]
There is a known problem, expect a new build soon.

**Comment by zpytela** [comment]
I suppose the problems are gone with the new selinux-policy-35.11-1.fc35 build, if not create a new issue.
