### ISSUE TITLE
neverallow violated by allow sandbox_* unlabeled_t:file { entrypoint };

### ISSUE THREAD

**Issue by wrabcak** [fedora-selinux/selinux-policy#113]
commit ef3466fd3ffe2e3b7ddcd886e6d3e349ce74a143
Author: Miroslav Grepl <mgrepl@redhat.com>
Date:   Tue Mar 22 09:49:22 2016 +0100

    Add neverallow assertion for unlabaled_t to increase policy security.

This commits violated this errors: 
libsepol.report_failure: neverallow violated by allow sandbox_x_client_t unlabeled_t:file { entrypoint };
libsepol.report_failure: neverallow violated by allow sandbox_net_client_t unlabeled_t:file { entrypoint };
libsepol.report_failure: neverallow violated by allow sandbox_x_t unlabeled_t:file { entrypoint };
libsepol.report_failure: neverallow violated by allow sandbox_web_client_t unlabeled_t:file { entrypoint };
libsepol.report_failure: neverallow violated by allow sandbox_min_t unlabeled_t:file { entrypoint };
libsepol.report_failure: neverallow violated by allow sandbox_net_t unlabeled_t:file { entrypoint };
libsepol.report_failure: neverallow violated by allow sandbox_web_t unlabeled_t:file { entrypoint };
libsepol.report_failure: neverallow violated by allow sandbox_min_client_t unlabeled_t:file { entrypoint };
libsepol.report_failure: neverallow violated by allow sandbox_t unlabeled_t:file { entrypoint };
libsepol.report_failure: neverallow violated by allow svirt_kvm_net_t unlabeled_t:file { entrypoint };
libsepol.report_failure: neverallow violated by allow svirt_lxc_net_t unlabeled_t:file { entrypoint };
libsepol.report_failure: neverallow violated by allow openshift_initrc_t unlabeled_t:file { entrypoint };
libsepol.report_failure: neverallow violated by allow svirt_qemu_net_t unlabeled_t:file { entrypoint };
libsepol.report_failure: neverallow violated by allow virtd_lxc_t unlabeled_t:file { entrypoint };

PS: ... and the second winner is ....

**Comment by rhatdan** [comment]
I think this neverallow rule is too strict.  We have lots of domains which are used for containers where the underlying files might not be labeled.

spc_t is a case where docker has disabled labeling of devicemapper devices but still has SELinux enabled on the machine, so we have a rule that says docker_t executing unlabeled_t gets spc_t.

**Comment by mgrepl** [comment]
See our ongoing conversation on selinux-internal-list and also our conversation with upstream.

**Comment by doverride** [comment]
I guess might be worth it to split out file/unlabeled again. Just because docker needs to be able to operate on file does not mean it is a good idea to also let that apply to unlabeled.

**Comment by rhatdan** [comment]
You mean break out unlabeled_t from UNKOWN_T.  Not sure how specifying a transition can happen on a file without a label versus one with a label that the kernel does not understand, makes a difference.

**Comment by doverride** [comment]
Well because an invalid label clearly means there is a something wrong with the consistency of policy versus labeling. Whereas no label means that the file system is not labeled (yet). Just saying that differentiating *might* be worth it in this case

**Comment by mgrepl** [comment]
Yes. I believe we really want to keep this rule. The another question is whether we have correct labeling - unlabeled_t for all cases here.

**Comment by doverride** [comment]
Anyway rhatdan: i think i understand what you are getting at. whether invalid label or no label at all you want spc_t to be able to operate on it. I think that probably sets a less-than-optimal precedence. I think i understand where you are coming from though. You want the experience to be painless.

Keep in mind though that by saying: "lets allow spc_t to operate on invalid and unlabeled objects" you are basically endorsing the presence of these, and if you are then you must assume that other processes may need some form of operation on these objects are well. You cannot assume that these mis -or unlabeled objects are only accessed by spc_t.

**Comment by mgrepl** [comment]
I understand both cases. I think we can add an attribute needed to "break" this neverallow check.

**Comment by pcmoore** [comment]
Yes, we need this neverallow rule; in my mind there is *never* a good reason for giving out access to unlabeled_t; unlabeled_t should be a sentinel type that indicates something has gone very wrong and needs to be dealt with by a real person (most likely a call to restorecon in the general use case).  Allowing access to unlabeled_t is a security risk and we shouldn't allow it.

If Docker, or any other application, needs access to unlabeled data, it should do a restorecon first and then access the data.

**Comment by doverride** [comment]
>  I think we can add an attribute needed to "break" this neverallow check.

That would really take the cake. nulling neverallow to null the unlabeled/file isids

**Comment by mgrepl** [comment]
@doverride  Well I don't understand you now. It is about "entrypoint" and I am talking about an attribute as we have for shadow_t for example.

**Comment by mgrepl** [comment]
But I agree with @pcmoore.

**Comment by doverride** [comment]
@mgrepl I suppose you're right. that was a bit ignorant of me. Sorry.

As for the entrypoint though, That ideally should not apply to just unlabeled_t in my view. It should apply to all types that arent entry_file_types()

**Comment by doverride** [comment]
This is what i have in DSSP:

```
	(neverallow subj_type_attribute not_entry_obj_type_attribute (file
		(entrypoint)))
```

**Comment by doverride** [comment]
Which roughly translates to: `dontaudit domain -exec_type:file entrypoint;`

**Comment by rhatdan** [comment]
I will try to get docker to label the content even if SELinux is disabled in docker.  Always mount with a context mount.

**Comment by wrabcak** [comment]
SELinux policy build looks fine with fixes by Mirek. 

Thank you guys.
