### ISSUE TITLE
wireplumber needs permissions to talk to bluez

### ISSUE THREAD

**Issue by fcrozat** [fedora-selinux/selinux-policy#1182]
Bluez has a experimental feature for bluetooth battery service, relying on wireplumber and dbus (similar to fwupd and bluetooth which is already covered in the policy)

This is causing some selinux complains: 
dbus-daemon[875]: [system] Rejected send message, 0 matched rules; type="method_return", sender=":1.72" (uid=1000 pid=4100 comm="/usr/bin/wireplumber" label="unconfined_u:unconfined_r:unconfined_t:s0->

This is on openSUSE Tumbleweed.

**Comment by zpytela** [comment]
@fcrozat, can you show avc denials? With full auditing enabled if possible.
```
1) Open the /etc/audit/rules.d/audit.rules file in an editor.
2) Remove the following line if it exists:
-a task,never
3) Add the following line to the end of the file:
-w /etc/shadow -p w
4) Restart the audit daemon:
  # service auditd restart
5) Re-run your scenario.
6) Collect AVC denials:
  # ausearch -i -m avc,user_avc,selinux_err,user_selinux_err -ts today
```

**Comment by fcrozat** [comment]
For some reasons, I can't reproduce the issue anymore. It might have been caused by an upgrade. Closing, I'll reopen if it reappears.
