### ISSUE TITLE
policy/modules/contrib points at a dead repo

### ISSUE THREAD

**Issue by keszybz** [fedora-selinux/selinux-policy#12]
http://oss.tresys.com/git/refpolicy-contrib.git is gone.

**Comment by wrabcak** [comment]
commit 46152fba614c8e1ed9277de3e536f19a5319951f
Author: Lukas Vrabec <lvrabec@redhat.com>
Date:   Mon Nov 3 14:34:24 2014 +0100

    Fix wrong url link to upstream.
