### ISSUE TITLE
Support for systemd /run/systemd/transient directory

### ISSUE THREAD

**Issue by keszybz** [fedora-selinux/selinux-policy#120]
https://github.com/systemd/systemd/commit/3959135139 added a new directory for unit files `/run/systemd/transient`. It should be labelled ` system_u:object_r:systemd_unit_file_t:s0`, the same as `/run/systemd/system`, PID 1 will write units there.

I'm seeing the following avc:

Apr 14 19:41:22 rawhide audit[1]: USER_AVC pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='avc:  denied  { start } for auid=n/a uid=0 gid=0 path="/run/systemd/transient/user-0.slice" cmdline="/usr/lib/systemd/systemd-logind" scontext=system_u:system_r:systemd_logind_t:s0 tcontext=system_u:object_r:init_var_run_t:s0 tclass=service exe="/usr/lib/systemd/systemd" sauid=0 hostname=? addr=? terminal=?'

**Comment by mgrepl** [comment]
Ok it looks reasonable. In which systemd version I can see the change to reproduce it?

Thank you.

**Comment by keszybz** [comment]
It's unreleased yet. It'll be in systemd-230.

**Comment by wrabcak** [comment]
Thank you for help @keszybz !
