### ISSUE TITLE
Allow systemd to read efivars

### ISSUE THREAD

**Issue by keszybz** [fedora-selinux/selinux-policy#121]
Apr 14 20:42:21 rawhide audit[1]: AVC avc:  denied  { read } for  pid=1 comm="systemd" name="LoaderTimeInitUSec-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f" dev="efivarfs" ino=9245 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:efivarfs_t:s0 tclass=file permissive=0

systemd tries to read a bunch of efi vars: `LoaderTimeInitUSec`, `LoaderTimeExecUSec`, `LoaderDevicePartUUID`. It's probably reasonable to allow it to read any `system_u:object_r:efivarfs_t:s0`.

**Comment by keszybz** [comment]
Relavant part of systemd code: https://github.com/systemd/systemd/blob/09541e49ebd17b41482e447dd8194942f39788c0/src/shared/efivars.c#L653-703

**Comment by keszybz** [comment]
In permissive mode:

Apr 14 20:55:00 rawhide kernel: audit: type=1400 audit(1460681700.163:45): avc:  denied  { read } for  pid=1 comm="systemd" name="LoaderTimeInitUSec-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f" dev="efivarfs" ino=9112 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:efivarfs_t:s0 tclass=file permissive=1
Apr 14 20:55:00 rawhide kernel: audit: type=1400 audit(1460681700.163:46): avc:  denied  { open } for  pid=1 comm="systemd" path="/sys/firmware/efi/efivars/LoaderTimeInitUSec-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f" dev="efivarfs" ino=9112 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:efivarfs_t:s0 tclass=file permissive=1

**Comment by wrabcak** [comment]
Commit ad2ebdab4061abde7ee3f8b35a2640ca604bb534 fixed this issue.
