### ISSUE TITLE
Unable to build target `policy`: 'syntax error' at token 'container_spc_stream_connect' on line 175053

### ISSUE THREAD

**Issue by DerbyKurby** [fedora-selinux/selinux-policy#1282]
I'm unable to build this policy from source on CentOS 9 Stream and Debian Testing. Regarding the [INSTALL](https://github.com/fedora-selinux/selinux-policy/blob/rawhide/INSTALL) doc, I'm failing on the policy target...

```
$> make install-src
$> make conf
$> make policy
Compiling refpolicy base module
/usr/bin/checkmodule base.conf -o tmp/base.mod
policy/modules/kernel/domain.te:707:ERROR 'syntax error' at token 'container_spc_stream_connect' on line 175053:
#line 707
    container_spc_stream_connect(domain)
/usr/bin/checkmodule:  error(s) encountered while parsing configuration
make: *** [Rules.modular:102: tmp/base.mod] Error 1
```

This even occurs on different branches (e.g. `f36` or tag like `v37.6`). Regarding the Fedora build pipeline, there're many changes - maybe someone can give me a hint how to build this directly from this upstream src.

Thanks.

**Comment by zpytela** [comment]
The interface is provided by container-selinux, you also need to install its sources.
https://github.com/containers/container-selinux

**Comment by zpytela** [comment]
Closing as there was no update in the past 2 weeks.
