### ISSUE TITLE
In the selinux policy.29 of fedora, can "httpd" access to "passwd_file_t"?

### ISSUE THREAD

**Issue by zfyseu** [fedora-selinux/selinux-policy#134]
Hello,everyone!
I have followed the link "https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Security-Enhanced_Linux/chap-Security-Enhanced_Linux-Targeted_Policy.html#sect-Security-Enhanced_Linux-Targeted_Policy-Confined_Processes" to examin the effect of selinux on fedora 23.
It did work. And "httpd" can't access to "samba_share_t".
However "httpd" can access to "passwd_file_t"  Besides there are not any rules between "httpd" and "passwd_file_t" when I use apol to search.
I don't know why? 
Is there anybody can tell me the reasons?
Thank you!

**Comment by vinzent** [comment]
there is no direct rule but an indirect one.

```
[notebook selinux-policy]$ sudo sesearch --allow -s httpd_t -t passwd_file_t
Found 3 semantic av rules:
   allow nsswitch_domain passwd_file_t : file { ioctl read getattr lock open } ; 
   allow httpd_t file_type : filesystem getattr ; 
   allow httpd_t file_type : dir { getattr search open } ; 
```

**Comment by mgrepl** [comment]
Yes, you are correct. It comes from 

        auth_use_nsswitch(httpd_t)

rule in apache.te to look up user, password, group, or host information.

**Comment by mgrepl** [comment]
Thank for your question.

**Comment by zfyseu** [comment]
Thank you all!
It's a great answer!
