### ISSUE TITLE
systemd: Unable to use LoadCredential with unix socket

### ISSUE THREAD

**Issue by umglurf** [fedora-selinux/selinux-policy#1541]
In addition to the problem with ramfs as described in #805, there is a second issue with LoadCredentials. LoadCredentials can point to a unix socket for getting the credentials, but this fails in the current policy. Tested on Fedora CoreOS 37 with starting a server using the following systemd socket file
```
[Unit]
Description=socket for wireguard credentials

[Socket]
ListenStream=/run/wg-credentials.socket
SocketUser=root
SocketGroup=root
SocketMode=0600

[Install]
WantedBy=sockets.target
```

When using in a service
```
LoadCredential=id:/run/wg-credentials.socket
```

it gives the following errors
```
type=AVC msg=audit(1672210323.355:1362): avc:  denied  { read } for  pid=4490 comm="(sd-mkdcreds)" name="wg-credentials.socket" dev="tmpfs" ino=1033 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=sock_file permissive=0
```

There should probably be defined a system folder for credentials sockets as a new SELinux type and `sd-mkdcreds` given access to sockes with this type

**Comment by zpytela** [comment]
@umglurf, we discussed this with systemd folks and it seems to be clear now https://github.com/systemd/systemd/blob/main/src/basic/fileio.c#L772

so it will probably be allowed for all sockets, but I'd like to see your use case described a bit if you can.

**Comment by umglurf** [comment]
Hi

My use case is to be able to use the unix socket functionality of LoadCredentials. I'll try to explain the whole flow.
I have services that I run with a wireguard tunnel and these needs access to wireguard credentials, for instance private and public key. These are stored in Hashicorp vault.

I have a `wg-credentials-server.socket` as shown, and also a `wg-credentials-server.service` that takes the socket from the socket unit and starts a small server. This server reads from the unix socket created by the systemd socket service, extracts the service and secret id from the peer name of the socket as described in the protocol for LoadCredentials. It then checks that the service is authorized, ie that it starts with `wg@' and if so, it connects to Hashicorp Vault, reads out the secret and writes it back to the socket.

I then have a general `wg@.service` that has 
```
LoadCredential=id:/run/wg-credentials.socket
LoadCredential=public_key:/run/wg-credentials.socket
LoadCredential=private_key:/run/wg-credentials.socket
etc
```
so that the `wg@.service` will have id, public_key, private_key, etc. These are read from Hashicorp Vault through the `wg-credentials-server` service. Some of the extra security features this gives are:
* The `wg-credentials-server` can run fully locked down (ProtectSystem=full, etc) and as an unprivileged user (DynamicUser=yes)
* The socket for `wg-credentials-server` is started by systemd and only root is able to access this socket.

It would be even better if selinux could restrict these kind of sockets so that only systemd can access these sockets and nobody else, not even root.

Hope that helped a bit, otherwise I can elaborate more.

**Comment by zpytela** [comment]
It was sufficient, thank you.

**Comment by zpytela** [comment]
Closing, feel free to review https://github.com/fedora-selinux/selinux-policy/pull/1577
or use the scratchbuild: Checks -> Artifacts -> rpms.zip

> It would be even better if selinux could restrict these kind of sockets so that only systemd can access these sockets and nobody else, not even root.

Unfortunately this cannot be done in SELinux. Try to use some of numerous systemd privacy options.
