### ISSUE TITLE
Split contrib and base in 2 git repository

### ISSUE THREAD

**Issue by mscherer** [fedora-selinux/selinux-policy#159]
I do not know why things arelike this, but that's something that do surprise lots of people, and that make things a bit more difficult to do (for example, you need to think about opening a PR on the right branch because master is not working, the default page show just a readme, etc, etc)

Any reason on keeping things this way ? (as I never found the reason for this setup)

**Comment by garyttierney** [comment]
ACK on this.  Currently cloning the repository via `git clone -b f25-base git@github.com:fedora-selinux/selinux-policy.git --recursive` produces a tree with a Fedora base policy and refpolicy contrib modules.  Trying to build / generate documentation for this tree results in a bunch of non obvious errors, and in the case that it does build, will produce an incorrect policy.

Can you consider fixing this situation?

**Comment by wrabcak** [comment]
Agree here, I'll split this repo.

**Comment by garyttierney** [comment]
Thanks @wrabcak!  It'd also be neat to have the API docs (i.e., `make html`, doc/html/) published like Tresys do but under the Fedora brand: http://oss.tresys.com/docs/refpolicy/api/.  I'm going to setup a CI job to publish them to my website in the meantime.

**Comment by wrabcak** [comment]
Hi, 
I created selinux-policy-contrib repo with contrib branches for fedora. 
https://github.com/fedora-selinux/selinux-policy-contrib
