### ISSUE TITLE
Missing context for mariadbd binary

### ISSUE THREAD

**Issue by CEbhNwPM** [fedora-selinux/selinux-policy#1669]
In MariaDB versions where `/usr/sbin/mysqld` is a symlink to `/usr/sbin/mariadbd` (to my knowledge at least the LTS versions 10.6 and 10.11 from the developer repos), the MariaDB server process has type `unconfined_service_t`, because the binary has type `bin_t`. From my understanding, it needs to have type `mysqld_exec_t`.

With selinux-policy versions that include [this commit](https://github.com/fedora-selinux/selinux-policy/commit/936db96bc825378ea7269a87540faab74f72a24d), services like PHP-FPM cannot connect to MariaDB via unix socket, for example, which is how I discovered this issue.

Adding the respective file context fixes the issue for me:
```bash
semanage fcontext -a -e /usr/sbin/mysqld /usr/sbin/mariadbd
restorecon -v /usr/sbin/mariadbd
systemctl restart mariadb
```

**Comment by zpytela** [comment]
Hi @CEbhNwPM
In Fedora there is mariadb-server-10.5.19 with symlinks only:
```
$ ls -lZ /usr/sbin/mysqld /usr/libexec/mysqld /usr/sbin/mariadbd /usr/libexec/mariadbd
-rwxr-xr-x. 1 root root system_u:object_r:mysqld_exec_t:s0 24241024 Nov 16 14:12 /usr/libexec/mariadbd
lrwxrwxrwx. 1 root root system_u:object_r:bin_t:s0                8 Nov 16 14:07 /usr/libexec/mysqld -> mariadbd
lrwxrwxrwx. 1 root root system_u:object_r:bin_t:s0               21 Nov 16 14:07 /usr/sbin/mariadbd -> /usr/libexec/mariadbd
lrwxrwxrwx. 1 root root system_u:object_r:bin_t:s0               19 Nov 16 14:07 /usr/sbin/mysqld -> /usr/libexec/mysqld
```
There should be no problem though to add the type for a regular file if turns out to be needed which would be the equivalent of:
```
semanage fcontext -a -t mysqld_exec_t -f f /usr/sbin/mariadbd
```
keeping bin_t for the case it is a symlink.

**Comment by CEbhNwPM** [comment]
Hello @zpytela,

it seems that all packages from rpm.mariadb.org put the binary in /usr/sbin. It looks like this for 10.5, 10.6 and 10.11 (with the manual context fix, of course):

```
$ ls -lZ /usr/sbin/mysqld /usr/libexec/mysqld /usr/sbin/mariadbd /usr/libexec/mariadbd
ls: cannot access '/usr/libexec/mysqld': No such file or directory
ls: cannot access '/usr/libexec/mariadbd': No such file or directory
-rwxr-xr-x. 1 root root system_u:object_r:mysqld_exec_t:s0 25250760 Jan 30 23:05 /usr/sbin/mariadbd
lrwxrwxrwx. 1 root root system_u:object_r:bin_t:s0                8 Jan 30 22:51 /usr/sbin/mysqld -> mariadbd
```

Is this difference in file locations a deliberate decision by Red Hat? Will the official SELinux policies support this in the future or should I raise this issue with the MariaDB developers instead?
In practice, everyone who runs a MariaDB version >= 10.6 on an RHEL 9-based system and wants to connect via socket (the default for phpMyAdmin) is going to run into this issue.

**Comment by zpytela** [comment]
@CEbhNwPM would this work for you?
https://github.com/fedora-selinux/selinux-policy/pull/1764
You can try a scratchbuild Checks -> Artifacts -> rpms.zip
It should have the same effect as the semanage command in my previous comment.
No other path is affected?

Regarding mariadb packaging, please talk to the maintainers.

**Comment by CEbhNwPM** [comment]
Yes, that would work, thank you. I had another look at the contexts of the binaries in the package (`MariaDB-server-0:10.11.4-1.el9.x86_64`) and it seems that everything else is fine.

**Comment by zpytela** [comment]
OK, I'll merge it, thanks for checking.
