### ISSUE TITLE
Consider changing default branch

### ISSUE THREAD

**Issue by driskell** [fedora-selinux/selinux-policy#195]
It's really useful to have a searchable repository, and unfortunately GitHub only allows search of the default branch.

As the default branch is master, with nothing but a README, this means the extremely useful search features are completely unusable.

Would you consider changing the default branch, to, perhaps, rawhide? It would then allow search functionality of the latest revisions. My use case is generally to lookup macro definitions to learn underlying functionalities, as I'm generally unable to find reliable documentation.

**Comment by wrabcak** [comment]
Hi, 
I understand, but because of branches reflecting Fedora releases, we agreed some time ago, that this better for understanding which policy is used for each Fedora release. I leave "master" branch empty just with readme, but I'll change default branch to rawhide. 

Thanks,
Lukas.
