### ISSUE TITLE
[RFE] Add  boolean to toggle the state of (some) policy capabilities

### ISSUE THREAD

**Issue by gkarakou** [fedora-selinux/selinux-policy#196]
I think it would provide a nice enhancement to alter the state of policy capabilities like always_check_network with a simple but effective boolean. That way one would not have to recompile the entire policy.

**Comment by ghost** [comment]
On Mon, May 01, 2017 at 11:13:31PM -0700, George Karakougioumtzis wrote:
> I think it would provide a nice enhancement to alter the state of policy capabilities like always_check_network with a simple but effective boolean. That way one would not have to recompile the entire policy.

requires selinux >= 2.4

echo '(policycap "always_check_network")' > always_check_network.cil && semodule -i always_check_network.cil

> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/fedora-selinux/selinux-policy/issues/196

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8  02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by ghost** [comment]
On Mon, May 01, 2017 at 11:13:31PM -0700, George Karakougioumtzis wrote:
> I think it would provide a nice enhancement to alter the state of policy capabilities like always_check_network with a simple but effective boolean. That way one would not have to recompile the entire policy.

the challenge shouldnt be adding a polcap, the challenge is removing one

> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/fedora-selinux/selinux-policy/issues/196

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8  02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by wrabcak** [comment]
@doverride 

Thanks for help! 

Closing this issue.
