### ISSUE TITLE
In minimum mode, GNOME startup error  (AVC denied)

### ISSUE THREAD

**Issue by gordonwwang** [fedora-selinux/selinux-policy#1973]
**Problem description:**

I have GNOME desktop installed in fc39 and it works fine.
Then I install selinux-policy-minimum and enable SELinux. 
Run the reboot command to restart the system. The following error occurs:
![image](https://github.com/fedora-selinux/selinux-policy/assets/53458548/d7ed367f-35f3-44bf-8a46-539d6fa1f632)

**Problem analysis:**
I check /var/log/audit/audit.log and find the following error. It looks like the SELinux policy is in trouble.
```
type=BPF msg=audit(1702556407.860:132): prog-id=78 op=UNLOAD
type=BPF msg=audit(1702556407.861:133): prog-id=79 op=LOAD
type=AVC msg=audit(1702556407.921:134): avc:  denied  { read } for  pid=1039 comm="(s-daemon)" name="mail" dev="dm-0" ino=16909781 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:mail_spool_t:s0 tclass=lnk_file permissive=0
```

**Additional information:**
1. I found that the Cinnamon desktop started normally in selinux-policy-minimum mode. This means that minimum mode should support graphical desktops.
2. The GNOME desktop can be started properly in targeted mode but fails to be started only in minimum mode.

So I think GNOME is having a problem in minimum mode.

**Comment by zpytela** [comment]
Thanks for reporting the issue, but the minimum policy only confines a few services so I am afraid it will not work with more complex services which are not confined. Please use targeted.
