### ISSUE TITLE
systemd-networkd denials on Fedora 39

### ISSUE THREAD

**Issue by daandemeyer** [fedora-selinux/selinux-policy#1991]
I'm seeing the following denials on Fedora 39 in a mkosi built VM running systemd-networkd:

```
Jan 08 11:52:41 fedora audit[374]: AVC avc:  denied  { watch } for  pid=374 comm="systemd-network" path="/run/dbus/system_bus_socket" dev="tmpfs" ino=143 scontext=system_u:system_r:systemd_networkd_t:s0 tcontext=system_u:object_r:system_dbusd_var_run_t:s0 tclass=sock_file permissive=1
Jan 08 11:52:42 fedora audit[374]: AVC avc:  denied  { watch } for  pid=374 comm="systemd-network" path="/run/dbus/system_bus_socket" dev="tmpfs" ino=143 scontext=system_u:system_r:systemd_networkd_t:s0 tcontext=system_u:object_r:system_dbusd_var_run_t:s0 tclass=sock_file permissive=1
```

systemd-networkd might be started before the dbus daemon is started, so it will wait using inotify for the dbus daemon to bind itself to the dbus socket for which the watch permission is required?

**Comment by zpytela** [comment]
There is something fishy with this: 
```
tcontext=system_u:object_r:system_bus_socket"
...
tcontext=system_u:object_r:system_dbusd_var_run_t:s0
```
The uneven quotation mark and doubled entries may indicate some unrelated problem.
There already is a watch rule for `/`, `/run`, `/run/dbus` since 2 years ago, not the socket file though.

If you have auditd running, can you share the audit logs?
Do you use some custom policy?

**Comment by daandemeyer** [comment]
@zpytela I made an error in copy pasting the output, please see the updated issue for the correct denial output. There is no custom policy and I'm not running auditd.

**Comment by zpytela** [comment]
There already is a watch rule for /, /run, /run/dbus since 2 years ago for the reasons you described, not the socket file: does it mean it started to be required by any change in the past 2 years?

https://github.com/fedora-selinux/selinux-policy/commit/569208d534

**Comment by daandemeyer** [comment]
@zpytela I cannot immediately find any related change in the past 2 years touching this functionality. The logic in systemd traverses the entire path of the socket and adds a watch for each directory and the socket itself. So it seems like the watch permission is required on the socket itself as well.

**Comment by daandemeyer** [comment]
@zpytela Any chance we could make the policy allow watch on the socket file itself as well? That would fix the final remaining denial when booting a mkosi built image in qemu.

**Comment by zpytela** [comment]
Is it required only for sd-networkd? Watching the rest of the path is allowed for 5 other services.

**Comment by daandemeyer** [comment]
@zpytela This same code is reused by all the other 5 services as well. I think the reason that this only turns up now is that this is basically a race condition between systemd-networkd starting and dbus-broker starting. If the dbus socket is created first and networkd tries to connect to it before dbus-broker starts listening on it, we'll create an inotify watch on it to get notified when we should try to connect again. I assume this specific order of events is rare or didn't happen before which is why we're only seeing this issue now.

**Comment by zpytela** [comment]
Do there was a change in the end.
I found out that 2 out of 5 domains were already allowed to watch that file, so now it's going to be synced.
