### ISSUE TITLE
some domains miss the map permission 

### ISSUE THREAD

**Issue by bachradsusi** [fedora-selinux/selinux-policy#201]
# ausearch -m avc,user_avc,selinux_err | grep " map " | audit2allow         
    
    
    #============= auditctl_t ==============
    allow auditctl_t auditd_etc_t:file map;
    
    #============= gpg_pinentry_t ==============
    allow gpg_pinentry_t user_tmp_t:file map;
    
    #============= insmod_t ==============
    allow insmod_t modules_object_t:file map;
    
    #============= lvm_t ==============
    allow lvm_t lvm_etc_t:file map;
    
    #============= pulseaudio_t ==============
    allow pulseaudio_t pulseaudio_home_t:file map;
    allow pulseaudio_t user_tmp_t:file map;
    
    #============= staff_t ==============
    allow staff_t cert_t:file map;
    allow staff_t v4l_device_t:chr_file map;
    
    #============= sysadm_t ==============
    allow sysadm_t auditd_etc_t:file map;
    allow sysadm_t auditd_log_t:file map;
    
    #============= xserver_t ==============
    allow xserver_t dri_device_t:chr_file map;
    allow xserver_t user_tmp_t:file map;
    allow xserver_t xserver_tmpfs_t:file map;

**Comment by bachradsusi** [comment]
allow semanage_t user_tmp_t:file map;

**Comment by bachradsusi** [comment]
allow staff_t mandb_cache_t:file map;

**Comment by wrabcak** [comment]
All AVCs should be fixed in the latest f27 build:
https://koji.fedoraproject.org/koji/buildinfo?buildID=969161

**Comment by bachradsusi** [comment]
Thanks! There's a missing rule for `pulseaudio_t`:

    ^_^ rpm -q selinux-policy                                                           
    selinux-policy-3.13.1-282.fc27.noarch
    
    ^_^ ausearch -i -m avc -ts recent | grep " map " | audit2allow                      
    #============= pulseaudio_t ==============     
    allow pulseaudio_t user_tmp_t:file map;

**Comment by wrabcak** [comment]
https://koji.fedoraproject.org/koji/taskinfo?taskID=21817398 new build.

**Comment by wrabcak** [comment]
Looks like this issue is fixed. Closing...
