### ISSUE TITLE
Scary looking allow rules for guest_usertype and xguest_usertype

### ISSUE THREAD

**Issue by UntoSten** [fedora-selinux/selinux-policy#221]
I have created a new restricted SELinux user. It is based it on existing guest_u.

Now what are these scary looking rules?

[root@localhost]# sesearch --allow|grep guest_usertype|grep admin
allow guest_usertype admin_home_t:dir { add_name getattr ioctl lock open read remove_name search write };
allow guest_usertype admin_home_t:lnk_file { getattr read };
allow xguest_usertype admin_home_t:dir { add_name getattr ioctl lock open read remove_name search write };
allow xguest_usertype admin_home_t:lnk_file { getattr read };

[root@localhost]# find / -type d -context '*admin_home_t*'
/root

Yes, DAC rules should prevent access to /root, but really, what is going on here?

**Comment by UntoSten** [comment]
This is on Fedora Linux 28, selinux-policy-targeted 3.14.1-40.

**Comment by wrabcak** [comment]
Well, this is a bug. 

If I exapand the rule:
./sepolicy-expander.sh "userdom_restricted_user_template(foo_t)" | grep admin
        (allow foo_t_usertype admin_home_t (dir (ioctl read write getattr lock add_name remove_name search open)))
        (allow foo_t_usertype admin_home_t (lnk_file (read getattr)))
        (typetransition foo_t_usertype admin_home_t file ".my.cnf" mysqld_home_t)

These rules should be removed:
 (allow foo_t_usertype admin_home_t (dir (ioctl read write getattr lock add_name remove_name search open)))
        (allow foo_t_usertype admin_home_t (lnk_file (read getattr)))

Labeling this ticket and will investigate it. 

Good catch!
