### ISSUE TITLE
Not able to remove unwanted domain transition to abrt_helper_t

### ISSUE THREAD

**Issue by UntoSten** [fedora-selinux/selinux-policy#222]
I have created a new highly restricted SELinux user, role and domain. Let's call it foo, it is based on guest_u on Fedora Linux 28. 

I have minimized allowed domain transitions *almost* to the point that I want, but analysis using

 sedta --source foo_t

still shows something bad:

###################################

Transition 4: foo_t -> abrt_helper_t

Domain transition rule(s):
allow domain abrt_helper_t:process transition;

Set execution context rule(s):
allow foo_t foo_t:process { dyntransition fork getattr getcap getpgid getrlimit getsched getsession noatsecure rlimitinh setcap setcurrent setexec setfscreate setkeycreate setpgid setrlimit setsched setsockcreate share sigchld siginh sigkill signal signull sigstop transition };

Entrypoint abrt_helper_exec_t:
    Domain entrypoint rule(s):
    allow abrt_helper_t abrt_helper_exec_t:file { entrypoint execute getattr ioctl lock map open read };

    File execute rule(s):
    allow domain abrt_helper_exec_t:file { execute getattr ioctl map open read };

    Type transition rule(s):
    type_transition foo_t abrt_helper_exec_t:process abrt_helper_t;

###################################

I have traced the origin of this to file policy/modules/kernel/domain.te.

Is there any chance of getting rid of this unwanted abrt_helper_t domain transition that is automatically allowed to domains? 

I guess I could just copy domain.fc, domain.te and domain.if, rename them and remove the transition right, but could this transition be removed from the official base policy? Or would it break too much?

**Comment by wrabcak** [comment]
Hi, 

Unfortunately, this is not possible, it's allowed for domain attribute so every subject on system could execute abrt_helper_exec_t binary. 

We could investigate if it's really needed and maybe remove it in future.

**Comment by wrabcak** [comment]
I'm closing this ticket because of inactivity and no possibility to remove domain transition rules from base selinux-policy.
