### ISSUE TITLE
SELinux policy in initramfs?

### ISSUE THREAD

**Issue by daandemeyer** [fedora-selinux/selinux-policy#2221]
I was wondering if it's possible and supported to include the SELinux policy in the initramfs? Is the policy designed taking the initramfs stage into account or is it solely designed to be loaded after switch-root from the initramfs into the rootfs? Or in other words, if I have the SELinux policy in the initramfs and every file labeled correctly, can I expect the system to boot or not?

**Comment by zpytela** [comment]
Normally, policy is loaded by systemd after switchroot.  I'd say it could work in initramfs, but what would be the benefit?

**Comment by daandemeyer** [comment]
@zpytela I don't know if it makes sense or not, I just wanted to check whether it's something I need to test. Given your comment and the number of denials I get when including and loading the policy in the initramfs, I'm guessing it's not something I should focus on.
