### ISSUE TITLE
userdom_change_password_template allows user to change shell

### ISSUE THREAD

**Issue by UntoSten** [fedora-selinux/selinux-policy#223]
Based on the template's name, one assumes that 

userdom_change_password_template()

would allow user to change his or her password. It does that.

But this template also allows executing files of type:

chfn_exec_t

And those include not only /usr/bin/chfn, but also /usr/bin/chsh:

[untosten@localhost]$ ls -lZ /usr/bin/{chfn,chsh}
-rws--x--x. 1 root root system_u:object_r:chfn_exec_t:s0 30256 Jul 16 14:56 /usr/bin/chfn
-rws--x--x. 1 root root system_u:object_r:chfn_exec_t:s0 25696 Jul 16 14:56 /usr/bin/chsh

This is quite bad. 

I want to make sure confined users run only my highly restricted custom shell, and it must not be changed by the user. So I replaced the template call with:

usermanage_run_passwd($1_t, $1_r)

Gotchas like this are not nice or good to security.

**Comment by wrabcak** [comment]
Hi @UntoSten 

So you used usermanage_run_passwd() instead of userdom_change_password_template() and right now it's working as you expected?  Did I understand it correctly?

**Comment by UntoSten** [comment]
Hi wraback!

Yes, I removed the call to userdom_change_password_template() and now I use usermanage_run_passwd()
instead. It allows the user to change passwords, so this works fine for me.

My restricted shell allows just two commands to users, so they could not have run chsh anyway, but it is good to have kernel level protection too with SELinux rules.

**Comment by UntoSten** [comment]
Maybe /usr/bin/chsh should have its own chsh_exec_t. 

Then I suppose userdom_change_password_template() would be more correct, even though it would still allow /usr/bin/chfn to change finger information.

**Comment by wrabcak** [comment]
I understand what you mean, however it's quite dangerous to remove something from this kind of template because new version could break the existing policies.

**Comment by UntoSten** [comment]
Yes, I see. It is very unfortunate that the template name suggests less rights than it in reality allows. 

Changing your password is one right, changing your shell is another, and they should never have been bundled together, especially in a template that has a potentially misleading name. I know I thought I was allowing just password change, not the right to change shell.

For the record, I have created a new SELinux user/role based on guest_u by creating copies of the m4-macros and by renaming them. For my purposes, all Fedora SELinux users/roles are too liberal. My new SELinux user must very restricted and to achieve that goal, I have investigated possibilities to remove as many as allow rules as possible. So when creating my SELinux user, I just never call the  userdom_change_password_template(). This works for me.

**Comment by UntoSten** [comment]
We could change /usr/bin/chsh to have its own unique type chsh_exec_t, and modify the template's definition so that it would allow executing chsh_exec_t and transitioning to chsh_t domain. That should preserve the semantics for those who call the template.

But it would still break policies that allow explicit access to chfn_exec_t. Currently they get access to /usr/bin/chsh, too, and after the change that would no longer hold. So it is probably too late to fix this by introducing a new type.

The good news is that we *CAN* fix this in a different way: Since this issue deals with a misleading template name, it affects only those who study and create SELinux policies. I would suggest adding a comment such as:

 NOTE! This template also allows user to change his or her shell!

In my opinion something like that should be included before the template definition *AND* before the places where the template calls are now made. That way everybody knows the behaviour they will get.

What do you think?

**Comment by wrabcak** [comment]
@doverride 
What do you think here? I'm afraid to change it to break "working" stuff. 

I have no problem with adding "NOTE!"

**Comment by UntoSten** [comment]
Hi wrabcak! 

You are right, we must not break existing stuff.

Adding comments should be enough, it is good documentation and makes things clear. Thanks a lot!

**Comment by ghost** [comment]
On Wed, Sep 05, 2018 at 03:28:36AM -0700, Lukas Vrabec wrote:
> @doverride 
> What do you think here? I'm afraid to change it to break "working" stuff. 

"userdom_change_passwd" is open to intepretation i suppose. It is not usermanage_run_passwd() so its not like you do not have options

I suppose you could edit the interface description making it clear that if you just want run "passwd" that you can use usermanage_run_passwd() instead.

> 
> I have no problem with adding "NOTE!"
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/fedora-selinux/selinux-policy/issues/223#issuecomment-418681215

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8  02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by UntoSten** [comment]
Hi doverride!

Seems like a good idea to add information about the possibility of using usermanage_run_passwd(). That could well be in the description. It would be helpful.

But like I said, I think it is important that the current calls to userdom_change_password_template() also contain a comment explaining that this template also allows changing shell. That comment is enough to make things clear for those who read that part of code, but do not visit the template definition. Sorry for being repetitive about this...

**Comment by wrabcak** [comment]
@UntoSten  will you create PR with this change based on comment from @doverride  ? :)

**Comment by ghost** [comment]
On Wed, Sep 05, 2018 at 07:28:07AM -0700, Unto Sten wrote:
> Hi doverride!
> 
> Seems like a good idea to add information about the possibility of using usermanage_run_passwd(). That could well be in the description. It would be helpful.
> 
> But like I said, I think it is important that the current calls to userdom_change_password_template() also contain a comment explaining that this template also allows changing shell. That comment is enough to make things clear for those who read that part of code, but do not visit the template definition. Sorry for being repetitive about this...

Yes that seems reasonable to me.

> 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/fedora-selinux/selinux-policy/issues/223#issuecomment-418751218

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8  02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by UntoSten** [comment]
> will you create PR with this change based on comment from @doverride ? :)

Yeah, I just did, but I was too tired and thought the template call was in selinux-policy-contrib. That is why there's two separate commits.

**Comment by wrabcak** [comment]
Closing because of #226
