### ISSUE TITLE
mandb_cache_t only allowed to staff_r why?

### ISSUE THREAD

**Issue by maage** [fedora-selinux/selinux-policy#233]
I don't understand why mandb_cache_t is only allowed to staff_r.

selinux-policy]$ git grep mandb_map_cache
policy/modules/roles/staff.te:    mandb_map_cache_files(staff_t)

When I have user role sysadm_r or user_r I am not able to access mandb_cache_t when I try to get manua of command that does not exits like:

```sh
man foo-does-not-exist
```

I think at least sysadm_r and unprivuser (user_r) should be able to use mandb.

```
# audit(1543950713.000:7399):
#  scontext="user_u:user_r:user_t:s0" tcontext="system_u:object_r:mandb_cache_t:s0"
#  class="file" perms="map"
#  comm="man" exe="" path=""
#  message="type=AVC msg=audit(1543950713.000:7399): avc:  denied  { map } for
#   pid=28717 comm="man" path="/var/cache/man/index.db" dev="sdc3" ino=20992383
#   scontext=user_u:user_r:user_t:s0 tcontext=system_u:object_r:mandb_cache_t:s0
#   tclass=file permissive=0"
```

Another issue is why there is something that is allowed to staff_r but not sysadm_r or am I understanding something wrong?

My system is: 

Fedora 29 x86_64

$ rpm -q selinux-policy
selinux-policy-3.14.2-42.fc29.noarch
$ rpm -q selinux-policy-targeted
selinux-policy-targeted-3.14.2-42.fc29.noarch

This commit does not help to diagnose but it allows staff_t to use mandb_cache_t:

https://github.com/fedora-selinux/selinux-policy/commit/f7f39867ea9aec9cc5d451feb2de3927bd612966

**Comment by wrabcak** [comment]
Because it was bug :) Fixed in: 2dc64e3bc9f1e50b4c7d91e370985198c5beefbe
