### ISSUE TITLE
Missing rules for bootupd part 2 (unmounted ESP)

### ISSUE THREAD

**Issue by travier** [fedora-selinux/selinux-policy#2341]
We need more rules for bootup for the case where the ESP is not mounted:

```
type=AVC msg=audit(1725385838.182:370): avc:  denied  { getattr } for  pid=3034 comm="bootupctl" path="/dev/vda1" dev="devtmpfs" ino=311 scontext=system_u:system_r:bootupd_t:s0 tcontext=system_u:object_r:fixed_disk_device_t:s0 tclass=blk_file permissive=1
```

Looks like it's because bootupd does a getattr to check if the device exists before mounting it.

```
type=AVC msg=audit(1725385843.983:373): avc:  denied  { setfscreate } for  pid=3046 comm="cp" scontext=system_u:system_r:bootupd_t:s0 tcontext=system_u:system_r:bootupd_t:s0 tclass=process permissive=1
```

~~I don't know why we did not catch this one before. It's part of the copy done by bootupd to update the bootloader.~~

I don't exactly know why we need this one / what it does. The call to `cp` is part of the copy done by bootupd to update the bootloader.

https://selinuxproject.org/page/ObjectClassesPerms is not clear.

**Comment by zpytela** [comment]
> I don't exactly know why we need this one / what it does. The call to cp is part of the copy done by bootupd to update the bootloader.

Is it a plain cp command or rather `cp -Z`?

**Comment by travier** [comment]
It's a `cp -a`: https://github.com/coreos/bootupd/blob/0f3de094a8c9eb965f4d7adad315c1beae7fe995/src/filetree.rs#L295..L296
