### ISSUE TITLE
dnsmasq needs leases files in /var/lib/NetworkManager/dnsmasq-.*\.leases

### ISSUE THREAD

**Issue by benzea** [fedora-selinux/selinux-policy#238]
When dnsmasq is run by network manager (for network sharing), the lease file is placed into `/var/lib/NetworkManager/`. This results in errors like:

```
Jan 07 15:04:18 ben-x1 NetworkManager[22928]: dnsmasq: cannot open or create lease file /var/lib/NetworkManager/dnsmasq-p2p-wlp4s0-10.leases: Permission denied
```

This changed in Network Manager with commit https://gitlab.freedesktop.org/NetworkManager/NetworkManager/commit/b4116a6fe6a5cfc05c0b81f71dd44b59c7ca0c43

**Comment by benzea** [comment]
Note that I believe this is not yet needed on current Fedora releases; however, I updated my Network Manager for testing purposes and am running into it.

**Comment by benzea** [comment]
Note that this is needed already for NetworkManager 1.14. So this does affect F30.

**Comment by wrabcak** [comment]
Hi, 

Could you share SELinux denials? 

1. # setenforce 0
2. try to reproduce your issue
3. ausearch -m AVC -ts recent 

Attach output of 3th step. 

Thanks,
Lukas.

**Comment by benzea** [comment]
I think the relevant part is:
```
time->Wed Jan 23 22:08:55 2019
type=AVC msg=audit(1548277735.093:5093): avc:  denied  { getattr } for  pid=1623 comm="dnsmasq" path="/run/NetworkManager/resolv.conf" dev="tmpfs" ino=3086032 scontext=system_u:system_r:dnsmasq_t:s0-s0:c0.c1023 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
```

There are a few more things that appeared at the same time though:
```
time->Wed Jan 23 22:08:55 2019
type=AVC msg=audit(1548277735.089:5086): avc:  denied  { getattr } for  pid=1623 comm="dnsmasq" path="/run/NetworkManager/resolv.conf" dev="tmpfs" ino=3086660 scontext=system_u:system_r:dnsmasq_t:s0-s0:c0.c1023 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
----
time->Wed Jan 23 22:08:55 2019
type=AVC msg=audit(1548277735.090:5087): avc:  denied  { getattr } for  pid=1410 comm="systemd-resolve" path="/run/NetworkManager/resolv.conf" dev="tmpfs" ino=3086660 scontext=system_u:system_r:systemd_resolved_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
----
time->Wed Jan 23 22:08:55 2019
type=AVC msg=audit(1548277735.091:5088): avc:  denied  { getattr } for  pid=1410 comm="systemd-resolve" path="/run/NetworkManager/resolv.conf" dev="tmpfs" ino=3086660 scontext=system_u:system_r:systemd_resolved_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
----
time->Wed Jan 23 22:08:55 2019
type=AVC msg=audit(1548277735.091:5089): avc:  denied  { getattr } for  pid=1410 comm="systemd-resolve" path="/run/NetworkManager/resolv.conf" dev="tmpfs" ino=3086660 scontext=system_u:system_r:systemd_resolved_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
----
time->Wed Jan 23 22:08:55 2019
type=AVC msg=audit(1548277735.091:5090): avc:  denied  { getattr } for  pid=1410 comm="systemd-resolve" path="/run/NetworkManager/resolv.conf" dev="tmpfs" ino=3086660 scontext=system_u:system_r:systemd_resolved_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
----
time->Wed Jan 23 22:08:55 2019
type=AVC msg=audit(1548277735.092:5091): avc:  denied  { getattr } for  pid=1410 comm="systemd-resolve" path="/run/NetworkManager/resolv.conf" dev="tmpfs" ino=3086660 scontext=system_u:system_r:systemd_resolved_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
----
time->Wed Jan 23 22:08:55 2019
type=AVC msg=audit(1548277735.092:5092): avc:  denied  { getattr } for  pid=1410 comm="systemd-resolve" path="/run/NetworkManager/resolv.conf" dev="tmpfs" ino=3086660 scontext=system_u:system_r:systemd_resolved_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
----
time->Wed Jan 23 22:08:55 2019
type=AVC msg=audit(1548277735.093:5093): avc:  denied  { getattr } for  pid=1623 comm="dnsmasq" path="/run/NetworkManager/resolv.conf" dev="tmpfs" ino=3086032 scontext=system_u:system_r:dnsmasq_t:s0-s0:c0.c1023 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
----
time->Wed Jan 23 22:08:55 2019
type=AVC msg=audit(1548277735.101:5094): avc:  denied  { getattr } for  pid=1410 comm="systemd-resolve" path="/run/NetworkManager/resolv.conf" dev="tmpfs" ino=3086032 scontext=system_u:system_r:systemd_resolved_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
----
time->Wed Jan 23 22:08:55 2019
type=AVC msg=audit(1548277735.102:5095): avc:  denied  { getattr } for  pid=1410 comm="systemd-resolve" path="/run/NetworkManager/resolv.conf" dev="tmpfs" ino=3086032 scontext=system_u:system_r:systemd_resolved_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
----
time->Wed Jan 23 22:08:55 2019
type=AVC msg=audit(1548277735.102:5096): avc:  denied  { getattr } for  pid=1410 comm="systemd-resolve" path="/run/NetworkManager/resolv.conf" dev="tmpfs" ino=3086032 scontext=system_u:system_r:systemd_resolved_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
----
time->Wed Jan 23 22:08:55 2019
type=AVC msg=audit(1548277735.102:5097): avc:  denied  { getattr } for  pid=1410 comm="systemd-resolve" path="/run/NetworkManager/resolv.conf" dev="tmpfs" ino=3086032 scontext=system_u:system_r:systemd_resolved_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
----
time->Wed Jan 23 22:08:55 2019
type=AVC msg=audit(1548277735.202:5107): avc:  denied  { getattr } for  pid=1099 comm="chronyd" path="/run/NetworkManager/resolv.conf" dev="tmpfs" ino=3086032 scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
----
time->Wed Jan 23 22:08:55 2019
type=AVC msg=audit(1548277735.202:5108): avc:  denied  { getattr } for  pid=1099 comm="chronyd" path="/run/NetworkManager/resolv.conf" dev="tmpfs" ino=3086032 scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
----
time->Wed Jan 23 22:08:55 2019
type=AVC msg=audit(1548277735.435:5128): avc:  denied  { getattr } for  pid=1099 comm="chronyd" path="/run/NetworkManager/resolv.conf" dev="tmpfs" ino=3086032 scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
----
time->Wed Jan 23 22:08:55 2019
type=AVC msg=audit(1548277735.436:5129): avc:  denied  { getattr } for  pid=1099 comm="chronyd" path="/run/NetworkManager/resolv.conf" dev="tmpfs" ino=3086032 scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
```

**Comment by benzea** [comment]
Hm, wait, no lease file error?

/me is confused and pokes things again

**Comment by benzea** [comment]
I was already running with "setenforce 0" and actually experimented a bit to make a MR to fix this issue. So I suspect my selinux policy is broken right now; will get back about it tomorrow.

**Comment by ghost** [comment]
Benjamin Berg <notifications@github.com> writes:

> I was already running with "setenforce 0" and actually experimented a bit to make a MR to fix this issue. So I suspect my selinux policy is
> broken right now; will get back about it tomorrow.

Make sure to remove any existing leases file.

It needs to "dnsmasq (wifi-ap) reads /etc/NetworkManager/dnsmasq-shared.d and mana…

…ges /var/lib/NetworkManager/dnsmasq*.leases"

https://github.com/DefenSec/dssp2-standard/commit/d82389762d6148112abaefc8e00dae0bb0597fb2

>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8 02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by ghost** [comment]
Benjamin Berg <notifications@github.com> writes:

> I think the relevant part is:

This is not relevant. This is relevant to auth_use_nsswitch() You have a
mislabeled /run/NetworkManager/resolv.conf and maybe more
>
> time->Wed Jan 23 22:08:55 2019
> type=AVC msg=audit(1548277735.093:5093): avc:  denied  { getattr } for  pid=1623 comm="dnsmasq" path="/run/NetworkManager/resolv.conf" dev="tmpfs" ino=3086032 scontext=system_u:system_r:dnsmasq_t:s0-s0:c0.c1023 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
>
> There are a few more things that appeared at the same time though:
>
> time->Wed Jan 23 22:08:55 2019
> type=AVC msg=audit(1548277735.089:5086): avc:  denied  { getattr } for  pid=1623 comm="dnsmasq" path="/run/NetworkManager/resolv.conf" dev="tmpfs" ino=3086660 scontext=system_u:system_r:dnsmasq_t:s0-s0:c0.c1023 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
> ----
> time->Wed Jan 23 22:08:55 2019
> type=AVC msg=audit(1548277735.090:5087): avc:  denied  { getattr } for  pid=1410 comm="systemd-resolve" path="/run/NetworkManager/resolv.conf" dev="tmpfs" ino=3086660 scontext=system_u:system_r:systemd_resolved_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
> ----
> time->Wed Jan 23 22:08:55 2019
> type=AVC msg=audit(1548277735.091:5088): avc:  denied  { getattr } for  pid=1410 comm="systemd-resolve" path="/run/NetworkManager/resolv.conf" dev="tmpfs" ino=3086660 scontext=system_u:system_r:systemd_resolved_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
> ----
> time->Wed Jan 23 22:08:55 2019
> type=AVC msg=audit(1548277735.091:5089): avc:  denied  { getattr } for  pid=1410 comm="systemd-resolve" path="/run/NetworkManager/resolv.conf" dev="tmpfs" ino=3086660 scontext=system_u:system_r:systemd_resolved_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
> ----
> time->Wed Jan 23 22:08:55 2019
> type=AVC msg=audit(1548277735.091:5090): avc:  denied  { getattr } for  pid=1410 comm="systemd-resolve" path="/run/NetworkManager/resolv.conf" dev="tmpfs" ino=3086660 scontext=system_u:system_r:systemd_resolved_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
> ----
> time->Wed Jan 23 22:08:55 2019
> type=AVC msg=audit(1548277735.092:5091): avc:  denied  { getattr } for  pid=1410 comm="systemd-resolve" path="/run/NetworkManager/resolv.conf" dev="tmpfs" ino=3086660 scontext=system_u:system_r:systemd_resolved_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
> ----
> time->Wed Jan 23 22:08:55 2019
> type=AVC msg=audit(1548277735.092:5092): avc:  denied  { getattr } for  pid=1410 comm="systemd-resolve" path="/run/NetworkManager/resolv.conf" dev="tmpfs" ino=3086660 scontext=system_u:system_r:systemd_resolved_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
> ----
> time->Wed Jan 23 22:08:55 2019
> type=AVC msg=audit(1548277735.093:5093): avc:  denied  { getattr } for  pid=1623 comm="dnsmasq" path="/run/NetworkManager/resolv.conf" dev="tmpfs" ino=3086032 scontext=system_u:system_r:dnsmasq_t:s0-s0:c0.c1023 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
> ----
> time->Wed Jan 23 22:08:55 2019
> type=AVC msg=audit(1548277735.101:5094): avc:  denied  { getattr } for  pid=1410 comm="systemd-resolve" path="/run/NetworkManager/resolv.conf" dev="tmpfs" ino=3086032 scontext=system_u:system_r:systemd_resolved_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
> ----
> time->Wed Jan 23 22:08:55 2019
> type=AVC msg=audit(1548277735.102:5095): avc:  denied  { getattr } for  pid=1410 comm="systemd-resolve" path="/run/NetworkManager/resolv.conf" dev="tmpfs" ino=3086032 scontext=system_u:system_r:systemd_resolved_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
> ----
> time->Wed Jan 23 22:08:55 2019
> type=AVC msg=audit(1548277735.102:5096): avc:  denied  { getattr } for  pid=1410 comm="systemd-resolve" path="/run/NetworkManager/resolv.conf" dev="tmpfs" ino=3086032 scontext=system_u:system_r:systemd_resolved_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
> ----
> time->Wed Jan 23 22:08:55 2019
> type=AVC msg=audit(1548277735.102:5097): avc:  denied  { getattr } for  pid=1410 comm="systemd-resolve" path="/run/NetworkManager/resolv.conf" dev="tmpfs" ino=3086032 scontext=system_u:system_r:systemd_resolved_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
> ----
> time->Wed Jan 23 22:08:55 2019
> type=AVC msg=audit(1548277735.202:5107): avc:  denied  { getattr } for  pid=1099 comm="chronyd" path="/run/NetworkManager/resolv.conf" dev="tmpfs" ino=3086032 scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
> ----
> time->Wed Jan 23 22:08:55 2019
> type=AVC msg=audit(1548277735.202:5108): avc:  denied  { getattr } for  pid=1099 comm="chronyd" path="/run/NetworkManager/resolv.conf" dev="tmpfs" ino=3086032 scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
> ----
> time->Wed Jan 23 22:08:55 2019
> type=AVC msg=audit(1548277735.435:5128): avc:  denied  { getattr } for  pid=1099 comm="chronyd" path="/run/NetworkManager/resolv.conf" dev="tmpfs" ino=3086032 scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
> ----
> time->Wed Jan 23 22:08:55 2019
> type=AVC msg=audit(1548277735.436:5129): avc:  denied  { getattr } for  pid=1099 comm="chronyd" path="/run/NetworkManager/resolv.conf" dev="tmpfs" ino=3086032 scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8 02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by benzea** [comment]
This is from a fresh RHEL 8 machine:
```
----
time->Thu Jan 24 08:40:58 2019
type=PROCTITLE msg=audit(1548337258.484:129): proctitle=2F7573722F7362696E2F646E736D617371002D2D636F6E662D66696C653D2F6465762F6E756C6C002D2D6E6F2D686F737473002D2D6B6565702D696E2D666F726567726F756E64002D2D62696E642D696E7465726661636573002D2D6578636570742D696E746572666163653D6C6F002D2D636C6561722D6F6E2D72656C6F61
type=SYSCALL msg=audit(1548337258.484:129): arch=c000003e syscall=257 success=yes exit=3 a0=ffffff9c a1=556d4dbeb700 a2=442 a3=1b6 items=0 ppid=946 pid=8452 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="dnsmasq" exe="/usr/sbin/dnsmasq" subj=system_u:system_r:dnsmasq_t:s0 key=(null)
type=AVC msg=audit(1548337258.484:129): avc:  denied  { append } for  pid=8452 comm="dnsmasq" path="/var/lib/NetworkManager/dnsmasq-wlp4s0.leases" dev="dm-0" ino=34487265 scontext=system_u:system_r:dnsmasq_t:s0 tcontext=system_u:object_r:NetworkManager_var_lib_t:s0 tclass=file permissive=1
type=AVC msg=audit(1548337258.484:129): avc:  denied  { create } for  pid=8452 comm="dnsmasq" name="dnsmasq-wlp4s0.leases" scontext=system_u:system_r:dnsmasq_t:s0 tcontext=system_u:object_r:NetworkManager_var_lib_t:s0 tclass=file permissive=1
type=AVC msg=audit(1548337258.484:129): avc:  denied  { add_name } for  pid=8452 comm="dnsmasq" name="dnsmasq-wlp4s0.leases" scontext=system_u:system_r:dnsmasq_t:s0 tcontext=system_u:object_r:NetworkManager_var_lib_t:s0 tclass=dir permissive=1
type=AVC msg=audit(1548337258.484:129): avc:  denied  { write } for  pid=8452 comm="dnsmasq" name="NetworkManager" dev="dm-0" ino=33985148 scontext=system_u:system_r:dnsmasq_t:s0 tcontext=system_u:object_r:NetworkManager_var_lib_t:s0 tclass=dir permissive=1
```

**Comment by benzea** [comment]
Just a reminder that this is probably still an issue :)

**Comment by wrabcak** [comment]
Hi All, 
Issue fixed in https://github.com/fedora-selinux/selinux-policy-contrib/commit/6ebb6cefd3b74e0c0878edf13084dfae93d967f9 

Thanks,
Lukas.
