### ISSUE TITLE
Updated Fedora 40 to 41 and now selinux-policy install doesn't seem correct based on failures I see

### ISSUE THREAD

**Issue by scottmarlow** [fedora-selinux/selinux-policy#2419]
Much of the history is tangled up in https://github.com/containers/podman/issues/24422 about not being able to run Podman.  

https://github.com/containers/podman/issues/24422#issuecomment-2452948878 is a good summary of likely two different issues in play.  I'm going to pause trying to troubleshoot/resolve further while others help (in case I am making things worse).  

Back to the Podman steps that are failing for me due to SELinux:
- podman run -it fedora /bin/bash
- podman ps -a
   - CONTAINER ID  IMAGE                                     COMMAND               CREATED        STATUS                    PORTS       NAMES 
   - f36598bf2429  registry.fedoraproject.org/fedora:latest  /bin/bash             3 minutes ago  Exited (0) 3 minutes ago              angry_payne 

Output of `journalctl -t setroubleshoot`:

> Nov 04 11:40:33 scottmarlow setroubleshoot[156566]: SELinux is preventing bash from 'read, write' accesses on the chr_file /dev/pts/0. For complete SELinux messages run: sealert -l 10fe10d1-3569-4a64-9fd0-dd9d74c40d0d
> Nov 04 11:40:33 scottmarlow setroubleshoot[156566]: SELinux is preventing bash from 'read, write' accesses on the chr_file /dev/pts/0.
>                                                     
>                                                     *****  Plugin catchall (100. confidence) suggests   **************************
>                                                     
>                                                     If you believe that bash should be allowed read write access on the 0 chr_file by default.
>                                                     Then you should report this as a bug.
>                                                     You can generate a local policy module to allow this access.
>                                                     Do
>                                                     allow this access for now by executing:
>                                                     # ausearch -c 'bash' --raw | audit2allow -M my-bash
>                                                     # semodule -X 300 -i my-bash.pp
>

**Comment by bachradsusi** [comment]
Most likely related to snapd-selinux and it should be already fixed in snapd-2.65.1-2.fc41 - https://src.fedoraproject.org/rpms/snapd/c/5d25d758dbb194041e637562e8e3b3739614a46e?branch=rawhide

Update snapd-selinux and reinstall container-selinux and it should work.

**Comment by scottmarlow** [comment]
Thanks @bachradsusi !

I just did a dnf update:
> dnf update

> Upgrading:
>  snap-confine 
> replacing snap-confine
> snapd
> replacing snapd
> snapd-selinux
> replacing snapd-selinux (snapd-selinux-0:2.65.1-2.fc41.noarch)

With `setenforce Enforcing`, Podman now works again for me!  :-)  Thank you so much SELinux team!
