### ISSUE TITLE
`/run/motd` and `/run/motd.d` paths not getting context `etc_t`

### ISSUE THREAD

**Issue by rfairley** [fedora-selinux/selinux-policy#242]
The changes in #230 and #232 gave `/run/motd` and `/run/motd.d(/.*)?` paths the context `etc_t`, which allows `sshd` to read these paths and display MOTD messages here.

Trying out the MOTD functionality (in a Fedora 29 cloud base Vagrant box), the paths still have the context `var_run_t` despite the setting to change the context to `etc_t` being present.

```
# dnf upgrade -y
...
# rpm -qa | grep "selinux-policy"
selinux-policy-targeted-3.14.2-46.fc29.noarch
selinux-policy-3.14.2-46.fc29.noarch
# ls -Z /run | grep motd
               system_u:object_r:var_run_t:s0 motd.d
# semanage fcontext -l | grep motd
...
/run/motd                                          regular file       system_u:object_r:etc_t:s0 
/run/motd.d(/.*)?                                  all files          system_u:object_r:etc_t:s0 
...
```

Doing the following gives the `/run/motd.d` path the `etc_t` context as desired, and the rule appears in the file contexts:

```
# semanage fcontext -a -t etc_t "/var/run/motd.d(/.*)?"
# restorecon -Rnv /run
Would relabel /run/motd.d from system_u:object_r:var_run_t:s0 to system_u:object_r:etc_t:s0
...
# semanage fcontext -l | grep motd
...
/run/motd                                          regular file       system_u:object_r:etc_t:s0 
/run/motd.d(/.*)?                                  all files          system_u:object_r:etc_t:s0 
...
/var/run/motd.d(/.*)?                              all files          system_u:object_r:etc_t:s0 
```

If adding a rule with the path `/run/motd.d(/.*)?`, the following error is given:

```
# semanage fcontext -a -t etc_t "/run/motd.d(/.*)?"
ValueError: File spec /run/motd.d(/.*)? conflicts with equivalency rule '/run /var/run'; Try adding '/var/run/motd.d(/.*)?' instead
```

It seems that adding the context for a path under `/run` is causing a conflict, and is why the change to give `/run/motd` and `/run/motd.d` context `etc_t` is not being propagated. I haven't verified this by building the policy with the changed settings on my system yet, though.

Would the best convention here be to change the paths in `policy/modules/kernel/files.fc` to `/var/run/motd` and `/var/run/motd.d(/.*)?`, in order to successfully label `/run/motd` and `/run/motd.d(/.*)?` with `etc_t`?

Thanks!

cc @dustymabe, @lucab, @LorbusChris

**Comment by dustymabe** [comment]
> Would the best convention here be to change the paths in `policy/modules/kernel/files.fc` to `/var/run/motd` and `/var/run/motd.d(/.*)?`, in order to successfully label `/run/motd` and `/run/motd.d(/.*)?` with `etc_t`?

probably, especially if it works. but I wonder what @wrabcak thinks

**Comment by LorbusChris** [comment]
nice detective work, @rfairley! If the proposed solution doesn't interfere elsewhere it sgtm, too.

**Comment by ghost** [comment]
Its probably time to remove the references to '/var/run', do not think there are many distributions left out there using it. certainly not fedora. this "feature" was implemented years ago and never finished because there was no incentive to complete the feature. Time to force the remainers to deal with it by removing support for it...

**Comment by rfairley** [comment]
> Its probably time to remove the references to '/var/run'

Makes sense to me - seems `/var/run` should be symlinked to `/run` in Fedora (following the latest freedesktop spec https://www.freedesktop.org/software/systemd/man/file-hierarchy.html#/var/run/). It looks like it'd be safe to replace references to `/var/run` with `/run`, with `/run` being aliased to `/var/run` already (https://github.com/fedora-selinux/selinux-policy/blob/rawhide/config/file_contexts.subs_dist#L14) (I think this is what causes the equivalence rule conflict).

Would the long term plan be to remove the alias, and replace `/var/run` references throughout the policy code with `/run`?

For now, I'll change the paths to start with `/var/run` to get a working patch.

**Comment by ghost** [comment]
Robert Fairley <notifications@github.com> writes:

>  Its probably time to remove the references to '/var/run'
>
> Makes sense to me - seems /var/run should be symlinked to /run in Fedora (following the latest freedesktop spec
> https://www.freedesktop.org/software/systemd/man/file-hierarchy.html#/var/run/). It looks like it'd be safe to replace references to /var/run
> with /run, with /run being aliased to /var/run already
> (https://github.com/fedora-selinux/selinux-policy/blob/rawhide/config/file_contexts.subs_dist#L14) (I think this is what causes the equivalence
> rule conflict).
>
> Would the long term plan be to remove the alias, and replace /var/run references throughout the policy code with /run?

I am saying that I think it is time to do this now. This /var/run > /run
endeavour has been ongoing to more than five years already. It is time
to remove the compatibility. If we don't do rhat and if Fedora does not
start to enforce /run then we'll still be sturggling with this in
another 5 years.

>
> For now, I'll change the paths to start with /var/run to get a working patch.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8 02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by dustymabe** [comment]
> Makes sense to me - seems `/var/run` should be symlinked to `/run` in Fedora

I think this is the case already:

```
[vagrant@vanilla-f29 ~]$ stat /var/run  | head -n 1
  File: /var/run -> ../run
```



> For now, I'll change the paths to start with `/var/run` to get a working patch.

sounds good. assuming @wrabcak agrees.

**Comment by LorbusChris** [comment]
I've taken a stab at removing the alias (and also the ones for /run/lock) over in #243 

I do not expect that to merge quickly, so we may still want to label /var/run/motd as a quick fix so it'll work for now?

**Comment by rfairley** [comment]
Nice, and agreed on the quick fix option. Will make that change to label the motd paths with `/var/run`.

**Comment by rfairley** [comment]
Opened a PR for the `/var/run` tweak: #244
