### ISSUE TITLE
SELinux prevents systemd from relabeling after loading the policy

### ISSUE THREAD

**Issue by ajeddeloh** [fedora-selinux/selinux-policy#270]
Sorry if this is the wrong place.

Systemd 240 introduced `/run/systemd/relabel-extra.d` ([doc](https://github.com/systemd/systemd/blob/master/NEWS#L1257)). Unfortunately the SELinux policy appears to be denying everything it's trying to do.

This is on Fedora CoreOS, which uses the normal Fedora systemd package.

Steps to reproduce: 
1) Boot fedora or fedora coreos with rd.break on the kernel command line
1) wait for the shell in the initrd
1) `echo '/etc' > /run/systemd/relabel-extra.d/foo.relabel`
1) continue booting (exit the shell)
1) observe AVC denials in the logs

**Comment by wrabcak** [comment]
Hi @ajeddeloh , 

Could you please  reproduce it and attach AVCs? 

Thanks,
Lukas.

**Comment by WOnder93** [comment]
> [...] prevents systemd from **reballing** [...]

Why does systemd need to catch eels? :) https://en.wiktionary.org/wiki/reballing

**Comment by ajeddeloh** [comment]
https://gist.github.com/ajeddeloh/14d9004e6156e71411f6d7e654673f1d < AVC logs

**Comment by wrabcak** [comment]
Thanks @ajeddeloh  for AVC logs. 

This is quite cool feature! I need to take a look to the code how it's implemented but it would be great if systemd could call restorecon or setfiles because there is already existing domain transition rule:
sesearch -T -s init_t -t setfiles_exec_t -c process
type_transition init_t setfiles_exec_t:process setfiles_t;

And all these AVC are generated because init_t cannot relabel files on the filesystem, but SELinux type setfiles_t could do it. 

Systemd guys, @keszybz, @poettering , @msekletar, 
Could you please take a look on this feature, how it's implemented and if we could run it in setfiles_t domain instead of init_t ?

Thanks,
Lukas.

**Comment by ghost** [comment]
On Tue, Aug 06, 2019 at 09:26:40AM -0700, Lukas Vrabec wrote:
> Thanks @ajeddeloh  for AVC logs. 
> 
> This is quite cool feature! I need to take a look to the code how it's implemented but it would be great if systemd could call restorecon or setfiles because there is already existing domain transition rule:
> sesearch -T -s init_t -t setfiles_exec_t -c process
> type_transition init_t setfiles_exec_t:process setfiles_t;
> 
> And all these AVC are generated because init_t cannot relabel files on the filesystem, but SELinux type setfiles_t could do it. 

If it would run setfiles in the setfiles_t domain then you would lose the ability to make this requested feature conditional.
systemd currently already relabels /dev, /dev/shm, /run, /sys/fs/cgroup, and that is mandatory (atleast /dev and /run (the others dont make sense)
Not to mention that systemd probably doesnt want a dependency on setfiles.

I would just accept the current implementation and create a boolean, something like: "systemd_relabel_all", when true allow it to relabel all, when false only allow it to relabel /dev /dev/shm /run /sys/fs/cgroup (current behavior)

You could use type attributes to group relabel rules that are common to systemd and setfiles for efficiency

> 
> Systemd guys, @keszybz, @poettering , @msekletar, 
> Could you please take a look on this feature, how it's implemented and if we could run it in setfiles_t domain instead of init_t ?
> 
> Thanks,
> Lukas.
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/fedora-selinux/selinux-policy/issues/270#issuecomment-518743758

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8 02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by keszybz** [comment]
~~It is is certainly possible, but I wonder if it is worth the trouble. IIUC, we would only be allowed to transition *to* `setfiles_exec_t`, but not back. We could work around this by doing the relabel in a child process. But then we have a bunch of code to fork off, wait, communicate the result back to the parent. It is certainly doable, but maybe it's just less trouble to add the rule?~~

Oh, I misread @wrabcak's comment. We certainly don't want to call an external binary.

I agree with what @doverride says. I wouldn't bother with the boolean though. No reason to make this conditional.

**Comment by poettering** [comment]
This is where the extra relabelling is done:

https://github.com/systemd/systemd/blob/master/src/core/mount-setup.c#L410

For everything listed in those files we do the exact relabel orgy as we do for /run, and everything else we relabel after the selinux policy is loaded.

**Comment by poettering** [comment]
btw, i don't think pid 1 should have blanket privs to relabel every file on the planet. absolutely not in fact.

if there's code in the initrd that wants stuff to be relabelled, then it should write our a relabel-extra.d/ file *AND* make sure that the selinux policy matches that.

Hence: if the project @ajeddeloh works on wants to relabel the whole of /etc (which sounds a bit drastic to me, but ok), then it should make sure itself that the the selinux policy coming with that project has the policy adapted like that, but not sure that is useful for the general case outside of that project? i.e. regular fedora should probably not allow pid 1 to relabel everything in /etc...

regarding doing the relabelling as different context: this would mean pid1 would have to change contexts, but I doubt that is really desirable? i mean, if pid 1 can change contexts like that, then it could as well just get rights to relabel everything on this planet

**Comment by ghost** [comment]
On Tue, Aug 06, 2019 at 11:52:04AM -0700, Lennart Poettering wrote:
> btw, i don't think pid 1 should have blanket privs to relabel every file on the planet. absolutely not in fact.
> 
> if there's code in the initrd that wants stuff to be relabelled, then it should write our a relabel-extra.d/ file *AND* make sure that the selinux policy matches that.
> 
> Hence: if the project @ajeddeloh works on wants to relabel the whole of /etc (which sounds a bit drastic to me, but ok), then it should make sure itself that the the selinux policy coming with that project has the policy adapted like that, but not sure that is useful for the general case outside of that project? i.e. regular fedora should probably not allow pid 1 to relabel everything in /etc...

Add a boolean that defaults to off, and limit it to non-security/non-auth file types, probably the most reasonable compromise as it catches most common scenarios whilst still protecting some sensitive files.
Systemd provides the functionality. Last thing one wants is that people disable selinux or try to alter the policy manually because it does not support some feature.

> 
> regarding doing the relabelling as different context: this would mean pid1 would have to change contexts, but I doubt that is really desirable? i mean, if pid 1 can change contexts like that, then it could as well just get rights to relabel everything on this planet

Should probably remove the existing transition rule for setfiles as its probably legacy bagage anyway.

> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/fedora-selinux/selinux-policy/issues/270#issuecomment-518797455

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8 02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by keszybz** [comment]
That's seems to put a very high bar on any users of this. Right now we have a very simple format that you can easily script and so on. Requiring plugging into selinux policy makes the whole thing much more complex. And anyway, compromised systemd can do anything, so worrying about a rogue relabel seems excessive.

**Comment by ghost** [comment]
On Tue, Aug 06, 2019 at 12:29:37PM -0700, Zbigniew Jędrzejewski-Szmek wrote:
> That's seems to put a very high bar on any users of this. Right now we have a very simple format that you can easily script and so on. Requiring plugging into selinux policy makes the whole thing much more complex. And anyway, compromised systemd can do anything, so worrying about a rogue relabel seems excessive. 

I suppose it can do everything before it loads the policy, but after that the policy *should* be able to limit its abilities quite a bit
For example it can't load policy on a system that already has a policy loaded, it can't access raw storage, memory, cpu
Can't access shadow directly. can't write policy etc etc.

> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/fedora-selinux/selinux-policy/issues/270#issuecomment-518810533

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8 02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by ajeddeloh** [comment]
>  if the project @ajeddeloh works on wants to relabel the whole of /etc (which sounds a bit drastic to me, but ok)

We don't need to relabel all of /etc, I was doing that as a test while debugging since it was easier to isolate the problem. We'll generate a list of specific files that need to be relabeled.

> and limit it to non-security/non-auth file types

I'm not sure what a security/auth file type means in this context, but I assume it means things like /etc/shadow and friends, amongst other things. These are files that we are looking to relabel as the project does things like creating and modifying users.

**Comment by ghost** [comment]
On Tue, Aug 06, 2019 at 01:10:49PM -0700, Andrew Jeddeloh wrote:
> >  if the project @ajeddeloh works on wants to relabel the whole of /etc (which sounds a bit drastic to me, but ok)
> 
> We don't need to relabel all of /etc, I was doing that as a test while debugging since it was easier to isolate the problem. We'll generate a list of specific files that need to be relabeled.
> 
> > and limit it to non-security/non-auth file types
> 
> I'm not sure what a security/auth file type means in this context, but I assume it means things like /etc/shadow and friends, amongst other things. These are files that we are looking to relabel as the project does things like creating and modifying users.

Ok then all non-security files (/etc/selinux/*/policy/policy.* , /etc/audit, /var/log/audit (some other audit files)

> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/fedora-selinux/selinux-policy/issues/270#issuecomment-518824910

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8 02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by keszybz** [comment]
> For example it can't load policy on a system that already has a policy loaded, it can't access raw storage, memory, cpu
Can't access shadow directly. can't write policy etc etc.

Sure it can. It is allowed to create units that start arbitrary commands with arbitrary options. Maybe in some super locked-down system things might be a bit different, but in general case if pid1 can run `dnf-automatic.service`, it can do any of those things.

**Comment by ghost** [comment]
On Tue, Aug 06, 2019 at 01:14:24PM -0700, Zbigniew Jędrzejewski-Szmek wrote:
> > For example it can't load policy on a system that already has a policy loaded, it can't access raw storage, memory, cpu
> Can't access shadow directly. can't write policy etc etc.
> 
> Sure it can. It is allowed to create units that start arbitrary commands with arbitrary options. Maybe in some super locked-down system things might be a bit different, but in general case if pid1 can run `dnf-automatic.service`, it can do any of those things.

True, package managers are a liability, and systemd is able to run them. Thats what systemd does, it runs things, and thats what package managers do they install stuff.
SELinux enforces integrity

SELinux is not the only tool in the toolbox though

> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/fedora-selinux/selinux-policy/issues/270#issuecomment-518826155

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8 02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by ghost** [comment]
On Tue, Aug 06, 2019 at 01:14:24PM -0700, Zbigniew Jędrzejewski-Szmek wrote:
> > For example it can't load policy on a system that already has a policy loaded, it can't access raw storage, memory, cpu
> Can't access shadow directly. can't write policy etc etc.
> 
> Sure it can. It is allowed to create units that start arbitrary commands with arbitrary options. Maybe in some super locked-down system things might be a bit different, but in general case if pid1 can run `dnf-automatic.service`, it can do any of those things.

Not "sure it can": that is pure speculation. It can run daemons (thats it).
Whether dnf or package managers in general can be a path to disable or manipulate selinux is a next step, and that can depend on more than just the selinux factor

I do get your point though, but it is not as black and white.

> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/fedora-selinux/selinux-policy/issues/270#issuecomment-518826155

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8 02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by bgilbert** [comment]
For context: the tool in question is [Ignition](http://github.com/coreos/ignition), which allows users to provision machines on first boot (similar to cloud-init).  Ignition runs from the initramfs.

> Ok then all non-security files (/etc/selinux/*/policy/policy.* , /etc/audit, /var/log/audit (some other audit files)

If the user specifies writing a file into `/etc/audit`, Ignition would like to be able to do it, and to arrange for that file to be labeled once policy is loaded.

**Comment by wrabcak** [comment]
Hi All, 

Thanks for your opinions. :) 
It's good point @doverride , @keszybz  that taking new dependency and calling external tool in systemd is not really clever idea. It make sense. 
Also I agree with @poettering that systemd should not relabel every object on the filesystem which also make sense. 

So... Solutions... I don't like boolean option because I'm pretty sure lot of people will forget to change the value of a boolean before reboot and then it breaks boot process. 
What about using setcon/setexeccon command to change the SELinux label of the process which relabels the objects defined in /run/systemd/relabel-extra.d ? With this, we could isolate process for relabeling in setfiles_t (or I can create some alias like systemd_relabel_t) domain without executing any external binary and there is also no need to add more allow rules to init_t (systemd pid 1) SELinux domain. 
setcon/setexeccon is part of libselinux-devel which is already systemd dependency. 

Thoughts?

**Comment by ghost** [comment]
On Wed, Aug 07, 2019 at 01:08:16PM -0700, Lukas Vrabec wrote:
> Hi All, 
> 
> Thanks for your opinions. :) 
> It's good point @doverride , @keszybz  that taking new dependency and calling external tool in systemd is not really clever idea. It make sense. 
> Also I agree with @poettering that systemd should not relabel every object on the filesystem which also make sense. 
> 
> So... Solutions... I don't like boolean option because I'm pretty sure lot of people will forget to change the value of a boolean before reboot and then it breaks boot process. 
> What about using setcon/setexeccon command to change the SELinux label of the process which relabels the objects defined in /run/systemd/relabel-extra.d ? With this, we could isolate process for relabeling in setfiles_t (or I can create some alias like systemd_relabel_t) domain without executing any external binary and there is also no need to add more allow rules to init_t (systemd pid 1) SELinux domain. 
> setcon/setexeccon is part of libselinux-devel which is already systemd dependency. 
> 
> Thoughts?    

I am against the idea of using setcon/setexeccon, but if it is decided to do it anyway then i would ask systemd to make sure that systemd handles it gracefully when the policy blocks this, and that it falls back to the current behavior.

> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/fedora-selinux/selinux-policy/issues/270#issuecomment-519249811

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8 02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by poettering** [comment]
it's pid 1 that relabels this stuff. It does so super-duper early, while mounting /dev and /proc and /run and stuff, before it goes and loads units and reads configuration files and stuff.

If we change PID 1 from init_t to relabel_t when relabelling, and then back to init_t, where's the effective difference from giving init_t full relabel rights anyway?

**Comment by poettering** [comment]
(what we could do is maybe have "preinit_t" or so, which PID 1 uses while doing some super basic stuff, like mounting /proc and this relabelling, and then dropping to regular init_t after that's done. Key here would be that there would be no way back however. i.e. iirc PID 1 gets started with the "kernel" label. We'd then load policy, transition to "preinit_t", then mount all those dirs, do relabelling, and then change to "init_t", and each of these transitions would be strictly one-way.

Question though is how to implement this nicely. Because right now init_t is not hardcoded, but read of the systemd binary. Not sure how to translate that into a new "preinit_t" label, where would we read that from?

**Comment by ghost** [comment]
On Thu, Aug 08, 2019 at 01:33:20AM -0700, Lennart Poettering wrote:
> (what we could do is maybe have "preinit_t" or so, which PID 1 uses while doing some super basic stuff, like mounting /proc and this relabelling, and then dropping to regular init_t after that's done. Key here would be that there would be no way back however. i.e. iirc PID 1 gets started with the "kernel" label. We'd then load policy, transition to "preinit_t", then mount all those dirs, do relabelling, and then change to "init_t", and each of these transitions would be strictly one-way.
> 
> Question though is how to implement this nicely. Because right now init_t is not hardcoded, but read of the systemd binary. Not sure how to translate that into a new "preinit_t" label, where would we read that from?

The way systemd currently transitions from kernel_t to init_t is also error prone i believe by the way but i can't think of a good alternative.
it uses the label of the systemd executable to compute whether it can transition and where to transition to. If that file is somehow mislabeled and systemd can't compute then its game over.

This is an issue with selinux-autorelabel

Consider the scenario:

you have a system without selinux policy. So everything is unlabeled.
then at runtime you install selinux-policy and you follow the suggested procedure:

fixfiles onboot && reboot

systemd looks up the label of its executable to determine where to transition to, but it has no label or in the case where you change a policy that is significantly different it has an invalid label

systemd can't compute and freezes, relabel doesnt happen. youre stuck.

> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/fedora-selinux/selinux-policy/issues/270#issuecomment-519423853

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8 02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by ghost** [comment]
On Thu, Aug 08, 2019 at 10:44:16AM +0200, Dominick Grift wrote:
> On Thu, Aug 08, 2019 at 01:33:20AM -0700, Lennart Poettering wrote:
> > (what we could do is maybe have "preinit_t" or so, which PID 1 uses while doing some super basic stuff, like mounting /proc and this relabelling, and then dropping to regular init_t after that's done. Key here would be that there would be no way back however. i.e. iirc PID 1 gets started with the "kernel" label. We'd then load policy, transition to "preinit_t", then mount all those dirs, do relabelling, and then change to "init_t", and each of these transitions would be strictly one-way.
> > 
> > Question though is how to implement this nicely. Because right now init_t is not hardcoded, but read of the systemd binary. Not sure how to translate that into a new "preinit_t" label, where would we read that from?
> 
> The way systemd currently transitions from kernel_t to init_t is also error prone i believe by the way but i can't think of a good alternative.
> it uses the label of the systemd executable to compute whether it can transition and where to transition to. If that file is somehow mislabeled and systemd can't compute then its game over.
> 
> This is an issue with selinux-autorelabel
> 
> Consider the scenario:
> 
> you have a system without selinux policy. So everything is unlabeled.
> then at runtime you install selinux-policy and you follow the suggested procedure:
> 
> fixfiles onboot && reboot
> 
> systemd looks up the label of its executable to determine where to transition to, but it has no label or in the case where you change a policy that is significantly different it has an invalid label
> 
> systemd can't compute and freezes, relabel doesnt happen. youre stuck.
> 

Maybe systemd should just proceed when it cannot compute its label, and instead rely on the policy?

> > 
> > -- 
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub:
> > https://github.com/fedora-selinux/selinux-policy/issues/270#issuecomment-519423853
> 
> -- 
> Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8 02D5 3B6C 5F1D 2C7B 6B02
> https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
> Dominick Grift



-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8 02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by wrabcak** [comment]
> it's pid 1 that relabels this stuff. It does so super-duper early, while mounting /dev and /proc and /run and stuff, before it goes and loads units and reads configuration files and stuff.
> 
> If we change PID 1 from init_t to relabel_t when relabelling, and then back to init_t, where's the effective difference from giving init_t full relabel rights anyway?

Understand, if it's PID 1 in very early state of booting process, it doesn't make sense to switch contexts and keep it in init_t. 
It looks like that the best way how to fix this issue is just to create SELinux boolean. 

Thank you all for help and investigating. 
Lukas.

**Comment by ghost** [comment]
On Fri, Aug 09, 2019 at 07:08:18AM -0700, Lukas Vrabec wrote:
> > it's pid 1 that relabels this stuff. It does so super-duper early, while mounting /dev and /proc and /run and stuff, before it goes and loads units and reads configuration files and stuff.
> > 
> > If we change PID 1 from init_t to relabel_t when relabelling, and then back to init_t, where's the effective difference from giving init_t full relabel rights anyway?
> 
> Understand, if it's PID 1 in very early state of booting process, it doesn't make sense to switch contexts and keep it in init_t. 
> It looks like that the best way how to fix this issue is just to create SELinux boolean. 

If youre worried about people forgetting to set the boolean true, then you can decide to default to on.
At least you have a way to lock it down if needed.

> 
> Thank you all for help and investigating. 
> Lukas.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/fedora-selinux/selinux-policy/issues/270#issuecomment-519933260

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8 02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by wrabcak** [comment]
Hi @doverride , 

Yes, it looks like this is the best solution.

**Comment by wrabcak** [comment]
@poettering, @keszybz, @msekletar,
Guys should I backport it also to Fedora 30? Or Rawhide is enough?

**Comment by keszybz** [comment]
I still think the boolean is just not worth the extra complexity and documentation effort, but either way, if the policy can be changed to allow this without requiring any other changes, that'd be great.

**Comment by ghost** [comment]
On Mon, Aug 12, 2019 at 08:31:22AM -0700, Zbigniew Jędrzejewski-Szmek wrote:
> I still think the boolean is just not worth the extra complexity and documentation effort, but either way, if the policy can be changed to allow this without requiring any other changes, that'd be great.

https://youtu.be/8cU4hQg6GvU?t=224

Some people aren't able to just get away with:

"THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU."

SELinux and integrity in general is not always about malicious activity.
It is also about being able to limit the damage done by flaws in code.

The boolean is enabled by default, so it should just works for people who dont care.
People that have a stake in integrity will have a way to lock it down.

I don't care either way since I use my own security policy, and you better believe that i pull systemd's teeth in there to the full extent.

> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/fedora-selinux/selinux-policy/issues/270#issuecomment-520474611

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8 02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by keszybz** [comment]
F30 would be good. We have systemd-241 in F30, so the bug would also manifest there.

**Comment by wrabcak** [comment]
So for some people bad news for some good news. We cannot use SELinux boolean for this issue because of m4 language limitation. I allowed it directly.

**Comment by ghost** [comment]
On Tue, Aug 13, 2019 at 08:39:05AM -0700, Lukas Vrabec wrote:
> So for some people bad news for some good news. We cannot use SELinux boolean for this issue because of m4 language limitation. I allowed it directly. 

This is not an m4 issue. You cannot associate types with type attributes in booleans.
The interface you call in the boolean associates the caller with can_relabelto_bin_policy and can_relabelto_shadow
These attributes are solely used to enforce neverallow rules, a functionality that is probably disabled anyway.
The solution would be to make the typeattributesets unconditional or if you dont use neverallow to just remove them.

Regardless, this is fine. I am already glad that this issue was resolved in a way that is transparent to systemd.

> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/fedora-selinux/selinux-policy/issues/270#issuecomment-520888689

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8 02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by bgilbert** [comment]
It appears that this has been fixed in F31 and Rawhide but not in F30.  Could the fix be backported to F30?  It's needed for live image support in Fedora CoreOS.

**Comment by wrabcak** [comment]
@bgilbert 
Backported. Fixes should be part of next F30 selinux-policy update.

**Comment by ajeddeloh** [comment]
Just pulled in the rpm to test and confirmed this fixes the problem. Thanks!

**Comment by wrabcak** [comment]
No problem, thanks for testing!
