### ISSUE TITLE
user_u can execute setuid binaries

### ISSUE THREAD

**Issue by Siosm** [fedora-selinux/selinux-policy#325]
According to the [Fedora 25 SELinux documentation](https://docs.fedoraproject.org/en-US/Fedora/25/html/SELinux_Users_and_Administrators_Guide/sect-Security-Enhanced_Linux-Introduction-Examples.html), users assigned with the SELinux `user_u` user should not be able to execute setuid binaries.

This is no longer the case at least on Fedora 31. Creating a confined user with:
```
$ sudo useradd test
$ sudo passwd test
$ sudo semanage login --add -s user_u -r s0 test

# Login as test
$ su -
# Accepts a valid root password and proceeds with setuid root
$ sudo -i
# Execute sudo
```

I have not yet found which commit undid this. This used to work until at least Fedora 29. I have not yet tested with Fedora 30.

**Comment by zpytela** [comment]
Thank you for reporting the issue, we will look at it and get back soon.

**Comment by Siosm** [comment]
While looking for the source of this specific issue, I found the following commits that appears to be problematic based on my current understanding of the policy:

* c309f5c0917d807cb0cd53b2daaa2407f7b7c569 -> allow unprivileged users to change **system** unit configurations instead of systemd **user** configuration.
* c2b42cb63ea82cd97590f8912a939ee4d55c6d5b -> enable access to both **system** systemd instances for unprivileged users.
* 6a0cb453ba0dcbbc7e75fa04a6647936ccdb339a -> allow unprivileged users to send signals to **system** systemd instances.

I think the main issue behind those three commits is that there does not appear to be a systemd_user_t type for systemd user instances running under unprivileged user_u users (it runs under user_t).

**Comment by langeman69** [comment]
Any progress on this? Fedora 33 is still suffering this issue :(

**Comment by zpytela** [comment]
Unfortunately there has no reasonable progress made, but we know it needs to be addressed.

**Comment by zpytela** [comment]
The problem has been fixed for F34 and rawhide: https://github.com/fedora-selinux/selinux-policy/pull/625
the commit will be a part of the next build. I will consider inclusion into F33 too.

Thanks for reporting, @travier.

**Comment by travier** [comment]
Thanks for doing that!
