### ISSUE TITLE
[Silverblue] RPMs that install to `/opt` have incorrect SELinux context type.

### ISSUE THREAD

**Issue by nlordell** [fedora-selinux/selinux-policy#335]
I believe there is a subtle SELinux policy bug that comes from the fact that RPMs that install to `/opt` instead get installed to `/usr/lib/opt` in Silverblue (for `ostree` reasons).

This causes a subtle policy bug because the expected SELinux context type for files installed to `/opt` is `usr_t`:
```
# semanage fcontext -l | grep -E '^/opt(/\.\* | )'
/opt                    all files          system_u:object_r:usr_t:s0
/opt/.*                 all files          system_u:object_r:usr_t:s0
```

However, since they get installed to `/usr/lib` instead, they pick up this rule:
```
# semanage fcontext -l | grep '^/usr/lib/\.\* '
/usr/lib/.*             all files          system_u:object_r:lib_t:s0
```

This causes RPMs which have files that install to `/opt` and rely on them having a `usr_t` context type to run into issues.

The solution, I think, would be to add a rule like so:
```
/usr/lib/opt            all files          system_u:object_r:usr_t:s0
/usr/lib/opt/.*         all files          system_u:object_r:usr_t:s0
```

Locally, I work around it by calling:
```
semanage fcontext -a -t usr_t '/usr/lib/opt(/.*)?'
```

**Comment by nlordell** [comment]
This is also an issue with files that are manually installed to `/opt` (for example when copying non-RPM binary distributions to `/opt`), where they get the `var_t` type because `/opt` is just a symlink to `/var/opt` and the following rule gets picked up:
```
# semanage fcontext -l | grep '^/var/\.\* '
/var/.*                 all files          system_u:object_r:var_t:s0
```

**Comment by zpytela** [comment]
@nlordell thank you for the detailed description.
I checked the Filesystem Hierarchy Standard document, and see 2 issues:

1. /var is IMHO correct, if there are files manually installed, the context needs to be set appropriately, using a semanage fcontext add or equivalency rule
2. /usr/lib/opt needs to be checked with Silverblue/ostree; although the current setting also complies with FHS, if it is continued to use this way, an equivalency rule:

/usr/lib/opt = /opt

may be considered, preferably in a related rpm package. Please open this issue with the respective team or in a mailing list.

If you want to test how it works, try the following command instead the one you posted:

semanage fcontext -a -e /opt /usr/lib/opt

**Comment by nlordell** [comment]
This all sounds very reasonable to me, and I admittedly know very little about SELinux. Thanks for the reply and for tip on setting an equivalency rule instead of adding a new one (are these equivalency rules similar to entries in the `*.subs_dist` files?).

Feel free to close the issue.

**Comment by zpytela** [comment]
@nlordell I think it is more a question of understanding all the layers and how components interact with each other in this case than just SELinux, so more developers may need to be involved to resolve a complex issue. I should have posted a link to FHS:
https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html

Equivalency rules work the same, either in distribution or as a user customization. The main value is when a nested path is used:
```
# matchpathcon /opt/cvs /usr/lib/opt/cvs
/opt/cvs        system_u:object_r:cvs_data_t:s0
/usr/lib/opt/cvs        system_u:object_r:cvs_data_t:s0
```

N.B.: I don't seem to have permissions to close other people's issues.
