### ISSUE TITLE
lircd needs some new permissions.

### ISSUE THREAD

**Issue by leamas** [fedora-selinux/selinux-policy#38]
since 0.9.2 (f22) lircd's default mode is to drop the root privileges and run as the system user 'lirc'. This causes AVC denials, muted by the following .te file:
```
    policy_module(lircd, 2)

    gen_require(`
      type lircd_t;
      type passwd_file_t;
    ')
    #============= lircd_t ==============
    allow lircd_t passwd_file_t:file { read getattr open };
    allow lircd_t self:capability { setuid setgid dac_override };
```
No idea what to do with this...

EDIT: lirc lives in fedora + EPEL.

**Comment by mgrepl** [comment]
It makes sense. Basically you want to submit a patch with

allow lircd_t self:capability { setuid setgid dac_override };
auth_read_passwd(lircd_t)

for lircd.te. 

See Wiki for more details how to do it.

Thank you  that you are testing it with enabled SELinux.

**Comment by leamas** [comment]
I'm so utterly lost here... is there a process document somewhere? The patch mechanics is no problem, but which is the file to patch?  userdomain.if ? And with the patched file at hand, how do I test it?

Feeling dumb.

**Comment by mgrepl** [comment]
Ok, no problem. I will update it by real examples to make it easier for understanding.

**Comment by leamas** [comment]
Here is seemingly some naming mess: https://lists.fedoraproject.org/pipermail/selinux/2015-September/016888.html

**Comment by leamas** [comment]
At last. Pull request #40 submitted , closing this bug. Sorry for the mess.
