### ISSUE TITLE
Wrong label on /var/spool/cron

### ISSUE THREAD

**Issue by DemiMarie** [fedora-selinux/selinux-policy#392]
`/var/spool/cron` is labelled `user_cron_spool_t`, which is incorrect and gives all daemons access to it.  It should be labeled `cron_spool_t`.

**Comment by wrabcak** [comment]
@zpytela  PTAL

**Comment by zpytela** [comment]
@DemiMarie, I wonder how you came across this issue, some security concerns?

While I agree `cron_spool_t` looks more appropriate, it has changed exactly from this type to `user_cron_spool_t` 9 years ago in commit f422c49a6543d8a15bcccdabcc7083f73e795bac. There is no further explanation, so not sure about the motivation.

Checking roughly the number of domains also looks as if there was no big difference:
```
  # sesearch -A -s daemon -t cron_spool_t -c dir | wc -l
78
  # sesearch -A -s daemon -t user_cron_spool_t -c dir | wc -l
77
```
For most of them, it is just `{ getattr open search }` anyway. There also seem to be very few different rule sets. There is a bunch of domains having access  to `cron_spool_t`, but not `user_cron_spool_t`.

Having said that, I can't see a problem using any of the types unless you are aware of some, but I also do not feel the urge to change it.

**Comment by zpytela** [comment]
@DemiMarie, was this answer sufficient?

**Comment by DemiMarie** [comment]
@zpytela if I recall correctly, the access granted wasn’t sufficient to do damage.  I will reopen if this becomes a problem.
