### ISSUE TITLE
Merging insmod_t and depmod_t types together

### ISSUE THREAD

**Issue by mgrepl** [fedora-selinux/selinux-policy#49]
Based on upstream communication we should merge these types together and have kmod_t. There is no security benefit to have have them as separate types. Even depmod is a symlink to kmod.

See 

http://oss.tresys.com/pipermail/refpolicy/2015-October/007758.html

for more details.

**Comment by wrabcak** [comment]
commit 45bf79c0a6cec51b02eae2fce323718d0e3ad3d7
Author: Lukas Vrabec <lvrabec@redhat.com>
Date:   Thu Dec 3 13:31:38 2015 +0100

    Merge insmod_t and depmod_t to kmod_t

Fixed in version: selinux-policy-3.13.1-162.fc24

**Comment by wrabcak** [comment]
@mgrepl  It took me 3.5years but I did it!
