### ISSUE TITLE
type syntax error

### ISSUE THREAD

**Issue by 1dot75cm** [fedora-selinux/selinux-policy#53]
@doverride 
I found some the "`type`" error in interface(`.if`).

> type syntax: `type TypeName [alias {alias1 alias2}] [,attribute1,attribute2];`
> require syntax: `require { component1; component2; }`
> available component: `class, user, role, type, attribute, bool`
（Book: SELinux by Example Using Security Enhanced Linux）

But I see the following statement. The "`urandom_device_t`" is the **attribute** or the second **type**? I have seen hundreds of such an approach in the interface.
```
# vi policy/modules/kernel/devices.if
4892 interface(`dev_read_urand',`
4893         gen_require(`
4894                 type device_t, urandom_device_t;
4895         ')
# grep -R "type.*,.*_t;" policy/modules/ | wc -l
465
```

The `gen_require` macro definition：
```
# vi policy/support/loadable_module.spt
 36 define(`gen_require',`
 37     ifdef(`self_contained_policy',`
 38         ifdef(`__in_optional_policy',`
 39             require {
 40                 $1
 41             } # end require
 42         ')
 43     ',`
 44         require {
 45             $1
 46         } # end require
 47     ')
 48 ')
```

So, This is the correct wording.
```
 gen_require(`
          type device_t; type urandom_device_t;
 ')
```

**Comment by doverride** [comment]
Aren't you supposed to be asleep?

I think this might be a mistake in the SELinux by example book, because I do not believe that this is a bug.

This should work fine:
```
 gen_require(`
          type device_t, urandom_device_t;
 ')
```

**Comment by 1dot75cm** [comment]
:), Yes, I searched for this page（http://selinuxproject.org/page/PolicyStatements）. 

> role, type, attribute, user, bool, sensitivity and category. The keyword is followed by one or more identifiers in a comma (,) separated list, with the last entry being terminated with a semi-colon (;).

In fact, the `require` block is not considered `type` of grammar. According to my understanding.

**Comment by 1dot75cm** [comment]
Thanks @doverride. Now, I can sleep well. have a nice day. :)))))))))))
