### ISSUE TITLE
Summary for userdom_user_tmp_content seems incorrect

### ISSUE THREAD

**Issue by jamielinux** [fedora-selinux/selinux-policy#56]
The summary for `userdom_user_tmp_content` doesn't seem correct.

https://github.com/fedora-selinux/selinux-policy/blob/d7237bffe494213af8656bc60a55b8330ee10239/policy/modules/system/userdomain.if#L1854

    Allow domain to attach to TUN devices created by administrative users.

`userdom_attach_admin_tun_iface` has exactly the same summary.

**Comment by doverride** [comment]
Copy and paste error, but i also find it important that interfaces have accurate summaries. I believe that this will, at least to some extend, lower the barrier of entrance for users. (people use the interface browser to look up what functionality interface provide, and if that is a mess then that is a turn off)

It's  kind of like a business card of SELinux policy.

**Comment by mgrepl** [comment]
Thank you for reporting this issue.

How about

        ##  Make the specified type usable as a
        ##  user temporary content.

**Comment by wrabcak** [comment]
Backported to F23 and F22. Thank you for report.
