### ISSUE TITLE
No version tags?

### ISSUE THREAD

**Issue by kloczek** [fedora-selinux/selinux-policy#564]
Looks like sonce last tagged release in Jan 2018 have been added +9.8k commits and during that time even one none of the new ersions has been tagged.
Is it possible to add just `<version>` tag of the last release?
(just version without dashes ot any additional strings in tag)

**Comment by bachradsusi** [comment]
I'm afraid there's no releases made in this repo. Fedora itself uses a snapshot of this repo  based on the latest commit in `rawhide` branch, see https://src.fedoraproject.org/rpms/selinux-policy/blob/rawhide/f/make-rhat-patches.sh

So how would you like to use this `<version>` tag? What it would be good for?

**Comment by kloczek** [comment]
So you as the maintainetr cannot make the relese of that repo?

**Comment by bachradsusi** [comment]
I'd like to understand how this release should look like, what it would be good for, and so on. This tag could be corresponding to some Fedora package version, or tag which says that Fedora 33 was branched at the moment, or some artificial number like `13`, or basically anything else.

**Comment by kloczek** [comment]
At the moment in Fedora is version 3.14.8 and here there is tag which could mark state of the code on 3.14.8 release.

**Comment by kloczek** [comment]
At the ame time at the moment is almost 10k commits added since last tagged version. Without tags it is not possible to veryfy what was on actual version which was used as base for Fedora.
Is it possible to make new version like 3.14.9 and tag it in git repo?

**Comment by zpytela** [comment]
We currently do not use tags in git repo and do not plan to, we do not have the build process based on using tags.

**Comment by kloczek** [comment]
So if tags marking versions are not used what is used instead?

**Comment by zpytela** [comment]
The latest rawhide branch commit at the moment of the package build, see the previous answers from bachradsusi.

**Comment by kloczek** [comment]
I'm not using rawhide.
So is it possible to add tag for least last version and keep adding such tags in the future? :P

**Comment by kloczek** [comment]
.. please :)

**Comment by zpytela** [comment]
@kloczek fyi we are currently discussing in the team if and how we could support tags.

**Comment by kloczek** [comment]
OK thx.

**Comment by zpytela** [comment]
@kloczek Tags have started to be used to mark the latest commit in a particular release, the pattern is "v+FedoraVersion+dot+OrderInTheFedoraVersion".

**Comment by kloczek** [comment]
Thank you :)

Closing ticket.

**Comment by zpytela** [comment]
Thank you for you patience, it really took more time than expected, hopefully it is now a part of the process, i. e. "error safe".
