### ISSUE TITLE
Interface is called `usedom` instead of `userdom`

### ISSUE THREAD

**Issue by jamielinux** [fedora-selinux/selinux-policy#57]
`usedom_dontaudit_user_getattr_tmp_sockets` interface has a name that differs from what one might expect.

Seen in `xserver.if` on [Line 1396](https://github.com/fedora-selinux/selinux-policy/blob/bb2ee60e8de5f783be5b4cd617c574e48978d9c3/policy/modules/services/xserver.if#L1396) and [Line 1397](https://github.com/fedora-selinux/selinux-policy/blob/bb2ee60e8de5f783be5b4cd617c574e48978d9c3/policy/modules/services/xserver.if#L1397).
Also seen in `userdomain.if` on [Line 2466](https://github.com/fedora-selinux/selinux-policy/blob/rawhide-base/policy/modules/system/userdomain.if#L2466).

**Comment by doverride** [comment]
This looks fine to me. The two interfaces in xserver.if are deprecated and redirecting to the one in userdomain.if

**Comment by doverride** [comment]
Oh err, sorry I overlooked the topic. Yes it should be userdom instead of usedom

**Comment by mgrepl** [comment]
Thank you, I added fixes.
