### ISSUE TITLE
/usr/libexec/abrt-hook-ccpp should have own domain

### ISSUE THREAD

**Issue by mgrepl** [fedora-selinux/selinux-policy#59]
We labeled /usr/libexec/abrt-hook-ccpp as abrt_dump_oops_exec_t to have it running in abrt_dump_t if it invoked by kernel. The problem is it want to access/create random files on a system. So it should go with a new domain which will be probably also unconfined domain.

**Comment by wrabcak** [comment]
Hi Mirek!
Do you have any idea of this new domain name? I agree with new domain and make it as unconfined domain.

**Comment by jfilak** [comment]
What about "core_dumper_t"? Anyway, please fix this issue ASAP.

**Comment by mgrepl** [comment]
We need to discuss it more.

**Comment by mgrepl** [comment]
Has been fixed by

https://github.com/fedora-selinux/selinux-policy/commit/38ee3cc4af928a1941426e1eff4fb11b5a355bfb
