### ISSUE TITLE
/etc/NetworkManager/VPN blocked by selinux in F34

### ISSUE THREAD

**Issue by imciner2** [fedora-selinux/selinux-policy#717]
The Fedora 34 selinux policy seems to be blocking access by NetworkManager to the `/etc/NetworkManager/VPN` directory by default now - which is causing a lot of selinux denial messages (about 1 every few seconds). That directory is one of the places that NetworkManger uses to detect VPN connections/plugins. The package isn't creating the directory anymore, but it could be present from older systems, and it is still being searched by the network manager daemon (hence the denials).

It would probably be good to mark that directory as allowed for NetworkManager to access.

(addendum: you can find the access to that directory in the NetworkManager code here: https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/blob/8232c3473f93a87e2eb736bf4b63049001a20926/src/core/vpn/nm-vpn-manager.c#L212)

rhbz: https://bugzilla.redhat.com/show_bug.cgi?id=1934725

**Comment by AdamWill** [comment]
This is already known, the issue serves no purpose. The bug was initially filed against selinux-policy and was already looked at by the maintainer, Zdenek Pytela. You can see his comments there.

**Comment by zpytela** [comment]
So in the end it will be addressed in selinux-policy.
https://github.com/fedora-selinux/selinux-policy/pull/718
