### ISSUE TITLE
kdump fails by selinux

### ISSUE THREAD

**Issue by liutgnu** [fedora-selinux/selinux-policy#727]
Hello, I have encountered a problem that selinux refused kdump to access to /var/lib/kdump/initramfs-*kdump.img.

In fedora, kexec-tools usually creates initramfs-*kdump.img in /boot partition. When /boot is read-only, it creates initramfs in /var/lib/kdump/ by patch [1]. The initramfs can be created successfully, however, when kexec-tools try to load the file, selinux give the following error log:

dracut[3697]: *** Creating initramfs image file '/var/lib/kdump/initramfs-5.13.0-0.rc0.20210428gitacd3d2859453.2.fc35.x86_64kdump.img' done ***
audit[5892]: AVC avc:  denied  { read } for  pid=5892 comm="kexec" name="initramfs-5.13.0-0.rc0.20210428gitacd3d2859453.2.fc35.x86_64kdump.img" dev="vda2" ino=67524 scontext=system_u:system_r:kdump_t:s0 tcontext=system_u:object_r:var_lib_t:s0 tclass=file permissive=0
kdumpctl[3435]: kdump: kexec: failed to load kdump kernel
kdumpctl[3435]: kdump: Starting kdump: [FAILED]

If I set selinux to be permissive mode, then kdump works fine.

**How to reproduce:**
1. On fedora rawhide (Currently patch [1] only in kexec-tools rawhide branch)
2. enable crashkernel option in kernel cmdline. Eg: on my machine, I have the following kernel cmdline:

$ cat /proc/cmdline
BOOT_IMAGE=(hd0,msdos1)/vmlinuz-5.13.0-0.rc0.20210428gitacd3d2859453.2.fc35.x86_64 root=UUID=359cd564-aca8-43aa-bd3f-b2412d1d319e ro rootflags=subvol=root console=ttyS0,115200n81 crashkernel=256M

3. dnf install -y kexec-tools
4. mount -o remount,ro /boot
5. systemctl start kdump (Oops)

**Expected behaviour:**

systemctl start kdump successfully.

I tried to modify the selinux policy but failed due to my lack of knowledge about selinux. Thanks in advance for any help!

[1] [https://lists.fedoraproject.org/archives/list/kexec@lists.fedoraproject.org/thread/G5LMDXOA46A7AXGQIXPZ3XU65H52D4I4/](https://lists.fedoraproject.org/archives/list/kexec@lists.fedoraproject.org/thread/G5LMDXOA46A7AXGQIXPZ3XU65H52D4I4/)

**Comment by zpytela** [comment]
@liutgnu it has been reported in https://bugzilla.redhat.com/show_bug.cgi?id=1951323
Thank you for the additional details which make it clearer.

Basically the solution consists of adding a private type for `/var/lib/kdump` and make `kdump_t` manage it.

**Comment by liutgnu** [comment]
@zpytela Thank you very much for the updating!

**Comment by zpytela** [comment]
@liutgnu closing this issue in favor of https://github.com/fedora-selinux/selinux-policy/pull/732 to continue the discussion there or in the bz. I am looking for other services accessing /var/lib/kdump.
