### ISSUE TITLE
SELinux is preventing rpcbind from 'name_bind' accesses on the udp_socket port

### ISSUE THREAD

**Issue by HuaxinLu** [fedora-selinux/selinux-policy#761]
I meet the same problem as https://bugzilla.redhat.com/show_bug.cgi?id=1758147. Someone said that turn on the nis_enabled bool flag can solved. But after turning it on, the problem still occurs probabilistically. 

I set nis_enabled to 1 and run this test script on f34:
```
# cat test.sh 
#!/bin/bash

for ((i=0;i<5000;i++));do
	service rpcbind restart
	sleep 3
	service rpcbind status | grep "could not bind" && echo "$i------" && break
done
```

This script stops at:
```
fedora rpcbind[14313]: rpcbind: svc_tli_create: could not bind to anonymous port
```

The result of audit2allow:
```
allow rpcbind_t traceroute_port_t:udp_socket name_bind;
```

rpcbind should bind a random udp port. The port range is defined at libtirpc/src/binddynport.c. And the default range is 49152~65534.

Should we add these rules to allow rpcbind_t to bind 49152~65534?

**Comment by zpytela** [comment]
selinux policy allows acces to ephemeral ports as defined in kernel:
```
# sysctl net.ipv4.ip_local_port_range
net.ipv4.ip_local_port_range = 32768    60999
```
If some service uses a different range, it should rather be fixed in the service to align with the default kernel settings.

**Comment by zpytela** [comment]
Closing this issue as no new information has appeared since half a year ago.
