### ISSUE TITLE
systemd-hwdb should be confined 

### ISSUE THREAD

**Issue by mgrepl** [fedora-selinux/selinux-policy#85]
$ ls -lZ /usr/bin/systemd-hwdb
-rwxr-xr-x. 1 root root system_u:object_r:bin_t:s0 70512 Dec 10 14:09 /usr/bin/systemd-hwdb

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/bin/systemd-hwdb update

**Comment by wrabcak** [comment]
https://github.com/fedora-selinux/selinux-policy/commit/8fe9871a1f2b50cfd55ff6dee41e9c001c3ad9d3
