### ISSUE TITLE
Fail to rasdaemon when SELINUX=enforcing

### ISSUE THREAD

**Issue by lujiev** [fedora-selinux/selinux-policy#860]
when setting the SELIINUX to enforcing, The rasdaemon function is unavailable and an error is reported 
“rasdaemon: page offline addr(0x208000f000) by /sys/devices/system/memory/soft_offline_page failed, errno:1”

The result of audit2allow:
allow rasdaemon_t  self:capability sys_admin;

Analysis shows that the implementation of soft_offline_page in the kernel determines whether have CAP_SYS_ADMIN,
The code is as follows:
/* Soft offline a page */
static ssize_t
store_soft_offline_page(struct device *dev,
			struct device_attribute *attr,
			const char *buf, size_t count)
{
	int ret;
	u64 pfn;
	**if (!capable(CAP_SYS_ADMIN))
		return -EPERM;**
	if (kstrtoull(buf, 0, &pfn) < 0)
		return -EINVAL;
	pfn >>= PAGE_SHIFT;
	if (!pfn_valid(pfn))
		return -ENXIO;
	/* Only online pages can be soft-offlined (esp., not ZONE_DEVICE). */
	if (!pfn_to_online_page(pfn))
		return -EIO;
	ret = soft_offline_page(pfn_to_page(pfn), 0);
	return ret == 0 ? count : ret;
}

**Comment by zpytela** [comment]
@lujiev, thanks for the analysis, this one should also be easy to address, will you?
