### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by lujiev** [fedora-selinux/selinux-policy#862]
https://github.com/fedora-selinux/selinux-policy/commit/5da0f01281f2aaacddb6c1edd57f747f26575f11

code 
    gen_require(`
        attribute unpriv_userdomain, userdomain;
    ')
    typeattribute $1  unpriv_userdomain;
    typeattribute $1  userdomain;

    auth_use_nsswitch($1)

Delete Code：typeattribute $1  unpriv_userdomain;
and  This line of code which   "attribute unpriv_userdomain, userdomain;"   should be modified to "attribute userdomain;"
"unpriv_userdomain" is not needed.

**Comment by zpytela** [comment]
@lujiev You are right, thanks for the catch. Would you mind creating a PR for that?
