### ISSUE TITLE
Sysprof denial on access to perf events from podman/toolbox

### ISSUE THREAD

**Issue by chergert** [fedora-selinux/selinux-policy#886]
F35 Host, F35 toolbox created with `toolbox create`/`toolbox enter`.

After that, using the `sysprof-cli` command within the container should connect to the host `/usr/libexec/sysprofd` via the system D-Bus.

However, `read()` on the perf FD passed over D-Bus fails from `sysprof-cli`.

```
Sep 21 16:17:02 workstation polkitd[7359]: Operator of unix-session:2 successfully authenticated as unix-user:christian to gain TEMPORARY authorization for action org.gnome.sysprof3.profile for system-bus-name::1.679 [sysprof-cli] (owned by unix-user:christia>
Sep 21 16:17:02 workstation audit[33253]: AVC avc:  denied  { read } for  pid=33253 comm="sysprof-cli" scontext=unconfined_u:system_r:spc_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=perf_event permissive=0
```

**Comment by chergert** [comment]
Note that the way this works is that the `sysprof-cli` requests a series of FDs for perf-event streams from `sysprofd` (on the host) which get mmap'd in the container/user process for reading.

**Comment by rhatdan** [comment]
unconfined domains should be allowed to read perf_event on all domains.

**Comment by zpytela** [comment]
The permissions should be changed in the next selinux-policy builds.
